-- =====================================================================
-- CRM Les Arts Culinaires — instalación desde cero
--
-- QUÉ ES ESTO
--   Todas las migraciones en orden, más los catálogos (vendedores,
--   programas, territorios, canales, etapas, estados y tipos de evento)
--   copiados de producción. Con esto una base de Supabase vacía queda
--   idéntica en estructura a la que usa ventas, pero SIN datos de clientes.
--
-- PARA QUÉ SIRVE
--   Para levantar el proyecto de PRUEBAS. Así se pueden probar cambios sin
--   tocar la base real.
--
-- CÓMO SE CORRE
--   Supabase → el proyecto NUEVO (no el de producción) → SQL Editor →
--   New query → pegar todo este archivo → Run. Una sola vez.
--
--   Es idempotente: si se corre dos veces no rompe nada ni duplica
--   catálogos. Aun así, correrlo en el proyecto equivocado no borra datos
--   pero sí agrega tablas; revisá dos veces que estés en el de pruebas.
--
-- DESPUÉS DE CORRERLO
--   1. Authentication → Sign In / Providers → apagar "Allow new users to
--      sign up" (igual que en producción).
--   2. Crear ahí un usuario administrador de prueba.
--
-- NO INCLUYE
--   Clientes, oportunidades ni notas. Son datos reales de personas y no
--   tienen por qué estar en un ambiente de pruebas. Si hace falta volumen
--   para probar, se cargan bases inventadas desde el propio módulo Bases.
-- =====================================================================


begin;


-- =====================================================================
-- 20260729173224_crm_esquema_normalizado.sql
-- =====================================================================

-- =====================================================================
-- CRM Les Arts Culinaires — Esquema para Supabase (PostgreSQL)
-- Ejecutar COMPLETO en: Supabase → SQL Editor → New query → Run
-- Luego importar los CSV en el orden 01..09 y ejecutar 02_post_import.sql
-- =====================================================================

-- ---------------------------------------------------------------- catálogos
create table if not exists public.vendedores (
  id          bigint generated by default as identity primary key,
  nombre      text not null unique,
  correo      text unique,
  activo      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.territorios (
  id     bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists public.canales (
  id     bigint generated by default as identity primary key,
  nombre text not null unique          -- Facebook, Instagram, WhatsApp, Referido...
);

create table if not exists public.productos (
  id         bigint generated by default as identity primary key,
  nombre     text not null unique,
  categoria  text not null default 'Otro'
             check (categoria in ('Diplomado','Curso corto','Certificación','Otro')),
  precio     numeric(12,2),            -- por llenar: precio de lista
  activo     boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.etapas (          -- pipeline
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  orden  smallint not null unique
);

create table if not exists public.estados (
  id       bigint generated by default as identity primary key,
  nombre   text not null unique,
  es_final boolean not null default false
);

-- ---------------------------------------------------------------- clientes
create table if not exists public.clientes (
  id                  bigint generated by default as identity primary key,
  nombre              text not null,
  telefono            text,
  telefono_secundario text,
  correo              text,
  territorio_id       bigint references public.territorios(id) on delete set null,
  activo              boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index if not exists idx_clientes_correo   on public.clientes (lower(correo));
create index if not exists idx_clientes_telefono on public.clientes (telefono);
create index if not exists idx_clientes_nombre   on public.clientes using gin (to_tsvector('spanish', nombre));

-- ---------------------------------------------------------------- oportunidades
create table if not exists public.oportunidades (
  id                  bigint generated by default as identity primary key,
  codigo              text unique,      -- CRM-0001 (código heredado del Excel)
  cliente_id          bigint not null references public.clientes(id)    on delete cascade,
  vendedor_id         bigint references public.vendedores(id)           on delete set null,
  producto_id         bigint references public.productos(id)            on delete set null,
  territorio_id       bigint references public.territorios(id)          on delete set null,
  canal_id            bigint references public.canales(id)              on delete set null,
  etapa_id            bigint references public.etapas(id)               on delete set null,
  estado_id           bigint references public.estados(id)              on delete set null,
  fecha_registro      date not null default current_date,
  fecha_cierre        date,
  valor_oportunidad   numeric(12,2) check (valor_oportunidad >= 0),
  venta_cerrada       numeric(12,2) check (venta_cerrada >= 0),
  descuento_promocion text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index if not exists idx_op_vendedor on public.oportunidades (vendedor_id);
create index if not exists idx_op_etapa    on public.oportunidades (etapa_id);
create index if not exists idx_op_estado   on public.oportunidades (estado_id);
create index if not exists idx_op_fecha    on public.oportunidades (fecha_registro);
create index if not exists idx_op_producto on public.oportunidades (producto_id);

-- ---------------------------------------------------------------- bitácora
create table if not exists public.oportunidad_notas (
  id             bigint generated by default as identity primary key,
  oportunidad_id bigint not null references public.oportunidades(id) on delete cascade,
  nota           text not null,
  origen         text not null default 'comentario',  -- de qué columna del Excel vino
  autor_id       uuid references auth.users(id) on delete set null,
  created_at     timestamptz not null default now()
);
create index if not exists idx_notas_op on public.oportunidad_notas (oportunidad_id);

-- ---------------------------------------------------------------- updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_clientes_updated on public.clientes;
create trigger trg_clientes_updated before update on public.clientes
  for each row execute function public.set_updated_at();

drop trigger if exists trg_oportunidades_updated on public.oportunidades;
create trigger trg_oportunidades_updated before update on public.oportunidades
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- vistas dashboard
--
-- Las vistas se tiran antes de crearlas. Más abajo `vw_pipeline` se vuelve a
-- definir con más columnas, y `create or replace view` no permite quitar ni
-- reordenar columnas: sin este drop, correr el archivo una segunda vez muere
-- con «cannot drop columns from view».
drop view if exists public.vw_pipeline;
drop view if exists public.vw_kpi_vendedor;
drop view if exists public.vw_embudo;

create or replace view public.vw_pipeline as
select o.id, o.codigo, o.fecha_registro,
       date_trunc('month', o.fecha_registro)::date as mes,
       c.nombre as cliente, c.telefono, c.correo,
       v.nombre as vendedor, p.nombre as producto, p.categoria,
       t.nombre as territorio, ca.nombre as canal,
       e.nombre as etapa, e.orden as etapa_orden,
       s.nombre as estado, s.es_final,
       o.valor_oportunidad, o.venta_cerrada, o.descuento_promocion
from public.oportunidades o
join public.clientes c   on c.id = o.cliente_id
left join public.vendedores  v  on v.id  = o.vendedor_id
left join public.productos   p  on p.id  = o.producto_id
left join public.territorios t  on t.id  = o.territorio_id
left join public.canales     ca on ca.id = o.canal_id
left join public.etapas      e  on e.id  = o.etapa_id
left join public.estados     s  on s.id  = o.estado_id;

create or replace view public.vw_kpi_vendedor as
select v.nombre as vendedor,
       count(*)                                              as total_oportunidades,
       count(*) filter (where s.nombre = 'Ganado')            as ganadas,
       round(100.0 * count(*) filter (where s.nombre = 'Ganado') / nullif(count(*),0), 1) as tasa_cierre_pct,
       coalesce(sum(o.venta_cerrada), 0)                      as monto_cerrado,
       coalesce(sum(o.valor_oportunidad), 0)                  as monto_en_pipeline
from public.oportunidades o
left join public.vendedores v on v.id = o.vendedor_id
left join public.estados    s on s.id = o.estado_id
group by v.nombre;

create or replace view public.vw_embudo as
select e.nombre as etapa, e.orden, count(o.id) as oportunidades,
       coalesce(sum(o.valor_oportunidad), 0) as valor
from public.etapas e
left join public.oportunidades o on o.etapa_id = e.id
group by e.nombre, e.orden
order by e.orden;

-- ---------------------------------------------------------------- RLS
-- Supabase expone las tablas vía API: sin RLS quedarían públicas.
alter table public.vendedores        enable row level security;
alter table public.territorios       enable row level security;
alter table public.canales           enable row level security;
alter table public.productos         enable row level security;
alter table public.etapas            enable row level security;
alter table public.estados           enable row level security;
alter table public.clientes          enable row level security;
alter table public.oportunidades     enable row level security;
alter table public.oportunidad_notas enable row level security;

-- Política inicial: cualquier usuario autenticado puede leer y escribir.
-- Endurecer después (ej. que cada vendedor vea solo sus oportunidades).
do $$
declare t text;
begin
  foreach t in array array['vendedores','territorios','canales','productos','etapas','estados',
                           'clientes','oportunidades','oportunidad_notas']
  loop
    execute format('drop policy if exists %I on public.%I', 'auth_all_'||t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (true) with check (true)',
      'auth_all_'||t, t);
  end loop;
end $$;


-- =====================================================================
-- 20260729174010_cerrar_fuga_vistas_security_definer.sql
-- =====================================================================

-- Ajustes aplicados sobre el esquema normalizado.
--
-- 1. Cierre de una fuga de datos: las vistas se habían creado como SECURITY
--    DEFINER (el comportamiento por defecto de Postgres), así que corrían con
--    los permisos de su creador y devolvían TODAS las filas a cualquiera con
--    la clave anónima, saltándose el RLS de las tablas.
-- 2. La vista de pipeline ahora expone también los id de cada catálogo, para
--    que la app pueda actualizar una oportunidad sin resolver por texto.
-- 3. Tablas de agenda, que el esquema original no contemplaba.

-- ------------------------------------------------------- vista de pipeline
-- Se recrea en vez de reemplazarse: `create or replace view` no permite
-- agregar columnas en medio del listado.
drop view if exists public.vw_pipeline;

create view public.vw_pipeline as
select o.id, o.codigo, o.fecha_registro, o.fecha_cierre,
       date_trunc('month', o.fecha_registro)::date as mes,
       o.cliente_id, c.nombre as cliente, c.telefono, c.correo,
       o.vendedor_id,   v.nombre  as vendedor,
       o.producto_id,   p.nombre  as producto, p.categoria,
       o.territorio_id, t.nombre  as territorio,
       o.canal_id,      ca.nombre as canal,
       o.etapa_id,      e.nombre  as etapa, e.orden as etapa_orden,
       o.estado_id,     s.nombre  as estado, s.es_final,
       o.valor_oportunidad, o.venta_cerrada, o.descuento_promocion
from public.oportunidades o
join public.clientes c   on c.id = o.cliente_id
left join public.vendedores  v  on v.id  = o.vendedor_id
left join public.productos   p  on p.id  = o.producto_id
left join public.territorios t  on t.id  = o.territorio_id
left join public.canales     ca on ca.id = o.canal_id
left join public.etapas      e  on e.id  = o.etapa_id
left join public.estados     s  on s.id  = o.estado_id;

-- security_invoker: la vista pasa a respetar el RLS de quien consulta.
alter view public.vw_pipeline     set (security_invoker = true);
alter view public.vw_kpi_vendedor set (security_invoker = true);
alter view public.vw_embudo       set (security_invoker = true);

-- search_path fijo: evita que un esquema malicioso en el search_path del
-- llamador secuestre las funciones que usa el trigger.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end $$;



-- =====================================================================
-- 20260729174325_vista_con_ids_y_tablas_agenda.sql
-- =====================================================================

-- Tablas de agenda: eventos de seguimiento colgados de cada oportunidad.
-- El esquema original no las contemplaba; el módulo Calendario las necesita.

-- ------------------------------------------------------------------ agenda
create table if not exists public.tipos_evento (
  id           smallint primary key,
  nombre       text not null unique,
  codigo       text not null,
  color        text not null,
  duracion_min smallint not null default 30 check (duracion_min > 0),
  orden        smallint not null default 0
);

create table if not exists public.eventos (
  id             bigint generated by default as identity primary key,
  oportunidad_id bigint not null references public.oportunidades(id) on delete cascade,
  tipo_id        smallint not null references public.tipos_evento(id),
  vendedor_id    bigint references public.vendedores(id) on delete set null,
  inicia_en      timestamptz not null,
  duracion_min   smallint not null default 30 check (duracion_min > 0),
  canal          text not null default 'Llamada'
                 check (canal in ('Presencial','Llamada','WhatsApp','Meet')),
  estado         text not null default 'Pendiente'
                 check (estado in ('Pendiente','Realizado','No se presentó','Reagendado')),
  resultado      text,
  proxima_accion text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists idx_eventos_oportunidad on public.eventos (oportunidad_id);
create index if not exists idx_eventos_inicia      on public.eventos (inicia_en);
create index if not exists idx_eventos_vendedor    on public.eventos (vendedor_id);

drop trigger if exists trg_eventos_updated on public.eventos;
create trigger trg_eventos_updated before update on public.eventos
  for each row execute function public.set_updated_at();

insert into public.tipos_evento (id, nombre, codigo, color, duracion_min, orden) values
  (0,'Llamada / videollamada','LL','#2F6FA8',30,0),
  (1,'Visita o tour al campus','TC','#B85042',60,1),
  (2,'Clase muestra o demo','CM','#8A5AA8',120,2),
  (3,'Envío de propuesta','PR','#0F6E7A',15,3),
  (4,'Seguimiento','SG','#6B665F',20,4),
  (5,'Recordatorio de pago','PG','#9C7118',15,5),
  (6,'Reactivación a 6 meses','RE','#2F6B4F',20,6)
on conflict (id) do nothing;

alter table public.tipos_evento enable row level security;
alter table public.eventos      enable row level security;

drop policy if exists auth_read_tipos_evento on public.tipos_evento;
create policy auth_read_tipos_evento on public.tipos_evento
  for select to authenticated using (true);

drop policy if exists auth_all_eventos on public.eventos;
create policy auth_all_eventos on public.eventos
  for all to authenticated using (true) with check (true);


-- =====================================================================
-- 20260730120000_usuarios_roles_permisos.sql
-- =====================================================================

-- Usuarios, roles y permisos.
--
-- Modelo: un usuario tiene un rol; un rol tiene permisos por módulo, con las
-- cuatro acciones de la pantalla (ver / crear / editar / eliminar).
--
-- `modulos` es un catálogo con jerarquía de un nivel: una fila con `padre`
-- apuntando a otra es un sub-permiso, que en la interfaz aparece indentado
-- como "Módulo — Detalle (sub-permiso)".

create table if not exists public.roles (
  id          bigint generated by default as identity primary key,
  nombre      text unique not null,
  descripcion text,
  activo      boolean not null default true,
  -- Un rol administrador siempre puede todo y no se puede borrar. Sirve de
  -- salvavidas: sin esto, quitarse permisos a uno mismo deja el CRM sin nadie
  -- que pueda volver a entrar a esta pantalla.
  es_admin    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.modulos (
  clave  text primary key,
  nombre text not null,
  -- Null en un módulo de primer nivel; la clave del padre en un sub-permiso.
  padre  text references public.modulos(clave) on delete cascade,
  orden  smallint not null default 0
);

create table if not exists public.rol_permisos (
  rol_id   bigint not null references public.roles(id)   on delete cascade,
  modulo   text   not null references public.modulos(clave) on delete cascade,
  ver      boolean not null default false,
  crear    boolean not null default false,
  editar   boolean not null default false,
  eliminar boolean not null default false,
  primary key (rol_id, modulo)
);

-- Un usuario de la aplicación, colgado de la cuenta de Supabase Auth.
create table if not exists public.usuarios (
  id         uuid primary key references auth.users(id) on delete cascade,
  nombre     text,
  correo     text not null,
  rol_id     bigint references public.roles(id) on delete set null,
  activo     boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_usuarios_rol on public.usuarios (rol_id);

drop trigger if exists trg_roles_updated on public.roles;
create trigger trg_roles_updated before update on public.roles
  for each row execute function public.set_updated_at();

drop trigger if exists trg_usuarios_updated on public.usuarios;
create trigger trg_usuarios_updated before update on public.usuarios
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- catálogo
insert into public.modulos (clave, nombre, padre, orden) values
  ('dashboard',        'Dashboard',            null, 10),
  ('clientes',         'Clientes',             null, 20),
  ('clientes.cliente', 'Editar datos del cliente', 'clientes', 21),
  ('clientes.notas',   'Registrar seguimiento',   'clientes', 22),
  ('pipeline',         'Pipeline',             null, 30),
  ('calendario',       'Calendario',           null, 40),
  ('equipos',          'Equipos',              null, 50),
  ('programas',        'Programas',            null, 60),
  ('usuarios',         'Usuarios y Roles',     null, 70)
on conflict (clave) do nothing;

insert into public.roles (nombre, descripcion, es_admin) values
  ('Administrador', 'Acceso completo al sistema', true),
  ('Ventas', 'Gestión de leads y seguimiento', false)
on conflict (nombre) do nothing;

-- El administrador arranca con todo encendido.
insert into public.rol_permisos (rol_id, modulo, ver, crear, editar, eliminar)
select r.id, m.clave, true, true, true, true
from public.roles r cross join public.modulos m
where r.es_admin
on conflict (rol_id, modulo) do nothing;

-- Ventas: todo menos administrar usuarios y sin borrar nada.
insert into public.rol_permisos (rol_id, modulo, ver, crear, editar, eliminar)
select r.id, m.clave, m.clave <> 'usuarios', m.clave <> 'usuarios', m.clave <> 'usuarios', false
from public.roles r cross join public.modulos m
where r.nombre = 'Ventas'
on conflict (rol_id, modulo) do nothing;

-- Toda cuenta que ya exista en Auth entra como administrador: si no, nadie
-- podría abrir esta pantalla para repartir los permisos.
insert into public.usuarios (id, nombre, correo, rol_id)
select u.id,
       coalesce(u.raw_user_meta_data->>'full_name', split_part(u.email, '@', 1)),
       u.email,
       (select id from public.roles where es_admin limit 1)
from auth.users u
on conflict (id) do nothing;

-- ---------------------------------------------------------------- RLS
--
-- `es_admin()` es SECURITY DEFINER a propósito: las políticas de `usuarios`
-- necesitan leer `usuarios` para decidir, y una política que se consulta a sí
-- misma entra en recursión infinita. Al correr como su creador, la función
-- salta el RLS y corta el ciclo.
create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select r.es_admin
    from public.usuarios u
    join public.roles r on r.id = u.rol_id
    where u.id = (select auth.uid()) and u.activo
  ), false);
$$;

revoke execute on function public.es_admin() from anon;

alter table public.roles        enable row level security;
alter table public.modulos      enable row level security;
alter table public.rol_permisos enable row level security;
alter table public.usuarios     enable row level security;

-- Todos los que iniciaron sesión leen el catálogo: la interfaz necesita saber
-- qué puede hacer el usuario antes de dibujar el menú.
drop policy if exists lee_roles on public.roles;
create policy lee_roles on public.roles
  for select to authenticated using (true);

drop policy if exists lee_modulos on public.modulos;
create policy lee_modulos on public.modulos
  for select to authenticated using (true);

drop policy if exists lee_permisos on public.rol_permisos;
create policy lee_permisos on public.rol_permisos
  for select to authenticated using (true);

-- Cada quien ve su propia ficha; el administrador ve y edita todas.
drop policy if exists lee_usuarios on public.usuarios;
create policy lee_usuarios on public.usuarios
  for select to authenticated
  using (id = (select auth.uid()) or public.es_admin());

-- Sólo el administrador reparte roles y permisos.
drop policy if exists admin_roles on public.roles;
create policy admin_roles on public.roles
  for all to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists admin_permisos on public.rol_permisos;
create policy admin_permisos on public.rol_permisos
  for all to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists admin_usuarios on public.usuarios;
create policy admin_usuarios on public.usuarios
  for all to authenticated using (public.es_admin()) with check (public.es_admin());

-- Impedir que se borre o se degrade el último rol administrador.
create or replace function public.protege_admin()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.es_admin then
      raise exception 'No se puede eliminar el rol administrador.';
    end if;
    return old;
  end if;

  if old.es_admin and not new.es_admin
     and not exists (select 1 from public.roles
                     where es_admin and id <> old.id) then
    raise exception 'Debe quedar al menos un rol administrador.';
  end if;
  return new;
end $$;

drop trigger if exists trg_protege_admin on public.roles;
create trigger trg_protege_admin before update or delete on public.roles
  for each row execute function public.protege_admin();


-- =====================================================================
-- 20260731120000_bases_importadas.sql
-- =====================================================================

-- (begin; lo maneja la transacción de este archivo)
-- Registro de las bases importadas.
--
-- CORRERLA COMPLETA, DE UNA VEZ. Va envuelta en una transacción a propósito:
-- más abajo hay que recrear `vw_pipeline` —no se le pueden agregar columnas
-- con `create or replace`— y entre el `drop` y el `create` la vista no
-- existe. Sin transacción, quien esté usando la app en ese instante recibe un
-- error. Con transacción nadie ve el hueco: o está la vista vieja, o la nueva.
--
-- Hasta ahora una importación dejaba las filas en `clientes` y
-- `oportunidades` y nada más: no quedaba rastro de qué archivo las trajo ni
-- cuándo. Esta tabla guarda ese encabezado, y cada oportunidad apunta a él.

create table if not exists public.importaciones (
  id          bigint generated by default as identity primary key,
  archivo     text not null,
  -- Cuántas filas se dieron de alta en esta corrida.
  filas       integer not null default 0,
  -- Quién la subió. Se conserva la importación aunque la cuenta se borre.
  creado_por  uuid references auth.users(id) on delete set null,
  creado_en   timestamptz not null default now()
);

create index if not exists ix_importaciones_creado_en
  on public.importaciones (creado_en desc);

-- `set null` y no `cascade`: borrar el registro de una base no debe borrar
-- los clientes que trajo.
alter table public.oportunidades
  add column if not exists importacion_id bigint
  references public.importaciones(id) on delete set null;

create index if not exists ix_oportunidades_importacion
  on public.oportunidades (importacion_id);

-- ---------------------------------------------------------------- vista
--
-- `created_at` e `importacion_id` se suman a la vista para que la pantalla
-- pueda agrupar por carga sin una consulta aparte. Hay que recrearla porque
-- `create or replace view` no admite agregar columnas en el medio.

drop view if exists public.vw_pipeline;

create view public.vw_pipeline as
select o.id, o.codigo, o.fecha_registro, o.fecha_cierre,
       date_trunc('month', o.fecha_registro)::date as mes,
       o.cliente_id, c.nombre as cliente, c.telefono, c.correo,
       o.vendedor_id,   v.nombre  as vendedor,
       o.producto_id,   p.nombre  as producto, p.categoria,
       o.territorio_id, t.nombre  as territorio,
       o.canal_id,      ca.nombre as canal,
       o.etapa_id,      e.nombre  as etapa, e.orden as etapa_orden,
       o.estado_id,     s.nombre  as estado, s.es_final,
       o.valor_oportunidad, o.venta_cerrada, o.descuento_promocion,
       o.created_at, o.importacion_id
from public.oportunidades o
join public.clientes c   on c.id = o.cliente_id
left join public.vendedores  v  on v.id  = o.vendedor_id
left join public.productos   p  on p.id  = o.producto_id
left join public.territorios t  on t.id  = o.territorio_id
left join public.canales     ca on ca.id = o.canal_id
left join public.etapas      e  on e.id  = o.etapa_id
left join public.estados     s  on s.id  = o.estado_id;

-- La vista respeta el RLS de quien consulta, igual que antes.
alter view public.vw_pipeline set (security_invoker = true);

-- ---------------------------------------------------------------- RLS

alter table public.importaciones enable row level security;

drop policy if exists auth_all_importaciones on public.importaciones;
create policy auth_all_importaciones on public.importaciones
  for all to authenticated using (true) with check (true);

-- (commit; lo maneja la transacción de este archivo)
-- =====================================================================
-- 20260731130000_autorizaciones.sql
-- =====================================================================

-- (begin; lo maneja la transacción de este archivo)
-- Autorizaciones de dirección general.
--
-- Sólo agrega: no toca ninguna tabla ni vista existente, así que se puede
-- correr con gente trabajando sin ningún riesgo.
--
-- Ventas pide, dirección resuelve. Que sólo un administrador pueda autorizar
-- no se deja a la interfaz: las políticas de abajo lo impiden a nivel de base,
-- así que tampoco se puede saltar llamando a la API directamente.

create table if not exists public.autorizaciones (
  id            bigint generated by default as identity primary key,
  nombre        text not null,
  descripcion   text not null default '',
  estado        text not null default 'pendiente'
                check (estado in ('pendiente', 'autorizada', 'rechazada')),
  -- Quién la pidió y cuándo.
  solicitado_por uuid references auth.users(id) on delete set null,
  solicitado_en  timestamptz not null default now(),
  -- Quién la resolvió. Nulos mientras siga pendiente.
  resuelto_por   uuid references auth.users(id) on delete set null,
  resuelto_en    timestamptz,
  -- Motivo de la decisión, sobre todo cuando se rechaza.
  comentario     text
);

create index if not exists ix_autorizaciones_estado
  on public.autorizaciones (estado, solicitado_en desc);

alter table public.autorizaciones enable row level security;

drop policy if exists autorizaciones_ver on public.autorizaciones;
drop policy if exists autorizaciones_pedir on public.autorizaciones;
drop policy if exists autorizaciones_resolver on public.autorizaciones;
drop policy if exists autorizaciones_borrar on public.autorizaciones;

-- Todo el equipo ve el tablero: saber qué está pendiente es parte del trabajo.
create policy autorizaciones_ver on public.autorizaciones
  for select to authenticated using (true);

-- Cualquiera pide, pero siempre en su propio nombre y siempre pendiente:
-- nadie se autoriza a sí mismo insertando una fila ya aprobada.
create policy autorizaciones_pedir on public.autorizaciones
  for insert to authenticated
  with check (
    estado = 'pendiente'
    and resuelto_por is null
    and resuelto_en is null
    and solicitado_por = (select auth.uid())
  );

-- Resolver es sólo de administradores. Acá está la regla de verdad.
create policy autorizaciones_resolver on public.autorizaciones
  for update to authenticated
  using (public.es_admin())
  with check (public.es_admin());

create policy autorizaciones_borrar on public.autorizaciones
  for delete to authenticated using (public.es_admin());

-- (commit; lo maneja la transacción de este archivo)
-- =====================================================================
-- catalogos.sql — catálogos copiados de producción (sin datos de clientes)
-- =====================================================================

-- vendedores
insert into public.vendedores (id, nombre, activo) values
  (1, 'Alexandra Ramos', true),
  (2, 'Huri Gomez', true),
  (3, 'Karla Rodriguez', true),
  (4, 'Katya Villatoro', true)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.vendedores', 'id'), coalesce((select max(id) from public.vendedores), 1));

-- territorios
insert into public.territorios (id, nombre) values
  (1, 'San Salvador'),
  (2, 'La Libertad'),
  (3, 'Santa Ana'),
  (4, 'Sonsonate'),
  (5, 'Ahuachapán'),
  (6, 'Usulután'),
  (7, 'Chalatenango'),
  (8, 'San Miguel'),
  (9, 'Cabañas'),
  (10, 'La Paz'),
  (11, 'Cuscatlán'),
  (12, 'San Vicente'),
  (13, 'La Unión'),
  (14, 'Morazán'),
  (15, 'Todos')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.territorios', 'id'), coalesce((select max(id) from public.territorios), 1));

-- canales
insert into public.canales (id, nombre) values
  (1, 'Instagram'),
  (2, 'Facebook'),
  (3, 'Whatsapp'),
  (4, 'Organico'),
  (5, 'Ex-alumnos'),
  (6, 'Alumna Activa'),
  (7, 'Referido'),
  (8, 'Passport')
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.canales', 'id'), coalesce((select max(id) from public.canales), 1));

-- productos
insert into public.productos (id, nombre, categoria, precio) values
  (1, 'Diplomado de Mixología', 'Diplomado', null),
  (2, 'Diplomado de Pasteleria', 'Diplomado', null),
  (3, 'Curso corto Bowl Fusion', 'Curso corto', null),
  (4, 'Curso corto Bolleria Francesa', 'Curso corto', null),
  (5, 'Curso corto Pastelería Saludable', 'Curso corto', null),
  (6, 'Información general', 'Otro', null),
  (7, 'Curso corto Cocina Nikkei', 'Curso corto', null),
  (8, 'Curso corto Les Petits Chefs', 'Curso corto', null),
  (9, 'Curso corto Mixología 360', 'Curso corto', null),
  (10, 'Diplomado Management Gastronómico', 'Diplomado', null),
  (11, 'Certificación', 'Certificación', null),
  (12, 'Diplomado de Cocina', 'Diplomado', null),
  (13, 'Diplomado de Barismo y Extracción de Café', 'Diplomado', null),
  (14, 'Dark Kitchen', 'Otro', null)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.productos', 'id'), coalesce((select max(id) from public.productos), 1));

-- etapas
insert into public.etapas (id, nombre, orden) values
  (1, 'Primer contacto', 1),
  (2, 'Propuesta', 2),
  (3, 'Negociación', 3),
  (4, 'Pago', 4),
  (5, 'Cierre', 5)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.etapas', 'id'), coalesce((select max(id) from public.etapas), 1));

-- estados
insert into public.estados (id, nombre, es_final) values
  (1, 'Activo', false),
  (2, 'Reserva', false),
  (3, 'En pausa/inactivo', false),
  (4, 'Ganado', true),
  (5, 'Perdido', true)
on conflict (id) do nothing;
select setval(pg_get_serial_sequence('public.estados', 'id'), coalesce((select max(id) from public.estados), 1));

-- tipos_evento
insert into public.tipos_evento (id, nombre, codigo, color, duracion_min) values
  (0, 'Llamada / videollamada', 'LL', '#2F6FA8', 30),
  (1, 'Visita o tour al campus', 'TC', '#B85042', 60),
  (2, 'Clase muestra o demo', 'CM', '#8A5AA8', 120),
  (3, 'Envío de propuesta', 'PR', '#0F6E7A', 15),
  (4, 'Seguimiento', 'SG', '#6B665F', 20),
  (5, 'Recordatorio de pago', 'PG', '#9C7118', 15),
  (6, 'Reactivación a 6 meses', 'RE', '#2F6B4F', 20)
on conflict (id) do nothing;
-- `tipos_evento.id` es smallint a mano, no serial: no hay secuencia que ajustar.

commit;
