begin;

-- Por qué se pierde un lead.
--
-- ------------------------------------------------------------------------
-- QUÉ RESUELVE
-- ------------------------------------------------------------------------
--
-- Hoy el CRM sabe cuántos leads se pierden pero no por qué, y ésas son dos
-- preguntas distintas: la primera se mira y se lamenta, la segunda se puede
-- hacer algo con ella. Si la mitad se pierde por «Muy caro» eso es una
-- conversación sobre precios; si es por «Problema de horario», sobre horarios.
--
-- ------------------------------------------------------------------------
-- CATÁLOGO Y NO TEXTO LIBRE
-- ------------------------------------------------------------------------
--
-- Con una casilla de texto, «muy caro», «Muy Caro» y «precio alto» serían tres
-- motivos distintos y la métrica no se podría sumar. Con un catálogo, agregar
-- un motivo sigue siendo una fila y no una migración.
--
-- ------------------------------------------------------------------------
-- LA REGLA QUE SE HACE CUMPLIR SOLA
-- ------------------------------------------------------------------------
--
-- Un motivo de pérdida en algo que no está perdido no significa nada. Pasa sin
-- mala intención: se marca «Perdido», se elige «Muy caro», y a la semana el
-- cliente vuelve y se lo pasa a «Activo». Sin nada que lo limpie, esa ficha
-- queda contando en la métrica de pérdidas para siempre. Un trigger lo borra
-- al salir de «Perdido», así que el número del tablero no puede mentir.
--
-- Sólo agrega una tabla, una columna y un trigger. Se puede correr con gente
-- trabajando, y dos veces.

-- ------------------------------------------------------------- el catálogo

create table if not exists public.motivos_perdida (
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  orden  smallint not null default 0,
  activo boolean not null default true
);

insert into public.motivos_perdida (nombre, orden) values
  ('Problema económico',      1),
  ('Problema de horario',     2),
  ('Muy caro',                3),
  ('Falta de documentación',  4),
  ('Dejó de contestar',       5),
  ('No interesado',           6)
on conflict (nombre) do nothing;

alter table public.motivos_perdida enable row level security;

-- Lo lee todo el equipo: hay que poder elegir un motivo. Cambiarlo es de
-- administración, como los programas: renombrar un motivo a mitad de un mes
-- parte la métrica en dos.
drop policy if exists motivos_ver on public.motivos_perdida;
create policy motivos_ver on public.motivos_perdida
  for select to authenticated using (true);

drop policy if exists motivos_administrar on public.motivos_perdida;
create policy motivos_administrar on public.motivos_perdida
  for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

-- --------------------------------------------------------------- la columna

alter table public.oportunidades
  add column if not exists motivo_perdida_id bigint
    references public.motivos_perdida(id) on delete set null;

comment on column public.oportunidades.motivo_perdida_id is
  'Por qué se perdió. Sólo tiene valor mientras el estado sea «Perdido»: un '
  'trigger lo limpia al salir de ahí.';

create index if not exists ix_op_motivo_perdida
  on public.oportunidades (motivo_perdida_id)
  where motivo_perdida_id is not null;

-- ------------------------------------------------- que no quede colgado

/**
 * Borra el motivo cuando la ficha deja de estar perdida.
 *
 * Se compara contra el id del estado «Perdido» buscado por nombre y no contra
 * un número escrito acá: los ids de los catálogos son de fábrica pero no son
 * una promesa, y una base restaurada de otra forma podría tenerlos distintos.
 *
 * Si no existe un estado llamado «Perdido» —una base a medio armar— el trigger
 * no borra nada en vez de borrarlo todo. Equivocarse hacia «no toco» es lo
 * correcto cuando lo que está en juego es un dato que alguien escribió.
 */
create or replace function public.limpiar_motivo_perdida()
returns trigger
language plpgsql
as $$
declare
  id_perdido bigint;
begin
  select id into id_perdido from public.estados where nombre = 'Perdido' limit 1;
  if id_perdido is null then
    return new;
  end if;

  if new.estado_id is distinct from id_perdido then
    new.motivo_perdida_id := null;
  end if;
  return new;
end $$;

drop trigger if exists trg_motivo_perdida on public.oportunidades;
create trigger trg_motivo_perdida
  before insert or update of estado_id, motivo_perdida_id on public.oportunidades
  for each row execute function public.limpiar_motivo_perdida();

-- ------------------------------------------------- que quede en el registro
--
-- El motivo se suma a las columnas que el registro de actividad vigila. Es un
-- dato que se discute —«¿por qué dijiste que se perdió?»— y sin esto el cambio
-- no dejaría rastro.

do $$
begin
  if exists (select 1 from pg_proc where proname = 'registrar_actividad') then
    drop trigger if exists trg_actividad_oportunidades on public.oportunidades;
    create trigger trg_actividad_oportunidades
      after insert or update or delete on public.oportunidades
      for each row execute function public.registrar_actividad(
        '{etapa_id,estado_id,vendedor_id,producto_id,territorio_id,canal_id,valor_oportunidad,venta_cerrada,fecha_cierre,descuento_promocion,motivo_perdida_id}',
        'oportunidad');
  else
    raise notice 'sin registro de actividad: el motivo no queda anotado';
  end if;
end $$;

-- --------------------------------------------------------------- la vista
--
-- `vw_pipeline` se rearma para que traiga el motivo con su nombre. Como en las
-- anteriores, las columnas que pueden faltar se preguntan en vez de escribirse
-- fijas: `importacion_id` y `reserva_en` las agregan migraciones que quizá no
-- se corrieron.

do $$
declare
  opcionales text := '';
begin
  if exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='oportunidades'
                and column_name='importacion_id') then
    opcionales := opcionales || ', o.importacion_id';
  end if;

  if exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='oportunidades'
                and column_name='reserva_en') then
    opcionales := opcionales || ', o.reserva_en';
  end if;

  drop view if exists public.vw_pipeline;

  execute format($vista$
    create view public.vw_pipeline as
    select o.id, o.codigo, o.fecha_registro, o.fecha_cierre,
           date_trunc('month', o.fecha_registro)::date as mes,
           o.cliente_id, c.nombre as cliente, c.telefono, c.correo,
           o.vendedor_id,   v.nombre  as vendedor,
           o.producto_id,   p.nombre  as producto, p.categoria,
           o.territorio_id, t.nombre  as territorio,
           o.canal_id,      ca.nombre as canal,
           o.etapa_id,      e.nombre  as etapa, e.orden as etapa_orden,
           o.estado_id,     s.nombre  as estado, s.es_final,
           o.motivo_perdida_id, mp.nombre as motivo_perdida,
           o.valor_oportunidad, o.venta_cerrada, o.reserva,
           o.descuento_promocion,
           o.created_at%s,
           c.edad,
           c.responsable_nombre,
           c.responsable_telefono,
           c.responsable_correo
    from public.oportunidades o
    join public.clientes c   on c.id = o.cliente_id
    left join public.vendedores  v  on v.id  = o.vendedor_id
    left join public.productos   p  on p.id  = o.producto_id
    left join public.territorios t  on t.id  = o.territorio_id
    left join public.canales     ca on ca.id = o.canal_id
    left join public.etapas      e  on e.id  = o.etapa_id
    left join public.estados     s  on s.id  = o.estado_id
    left join public.motivos_perdida mp on mp.id = o.motivo_perdida_id
  $vista$, opcionales);

  -- Como siempre: la vista mira con los permisos de quien pregunta.
  execute 'alter view public.vw_pipeline set (security_invoker = true)';
end $$;

commit;
