-- Usuarios, roles y permisos.
--
-- Modelo: un usuario tiene un rol; un rol tiene permisos por módulo, con las
-- cuatro acciones de la pantalla (ver / crear / editar / eliminar).
--
-- `modulos` es un catálogo con jerarquía de un nivel: una fila con `padre`
-- apuntando a otra es un sub-permiso, que en la interfaz aparece indentado
-- como "Módulo — Detalle (sub-permiso)".

create table if not exists public.roles (
  id          bigint generated by default as identity primary key,
  nombre      text unique not null,
  descripcion text,
  activo      boolean not null default true,
  -- Un rol administrador siempre puede todo y no se puede borrar. Sirve de
  -- salvavidas: sin esto, quitarse permisos a uno mismo deja el CRM sin nadie
  -- que pueda volver a entrar a esta pantalla.
  es_admin    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.modulos (
  clave  text primary key,
  nombre text not null,
  -- Null en un módulo de primer nivel; la clave del padre en un sub-permiso.
  padre  text references public.modulos(clave) on delete cascade,
  orden  smallint not null default 0
);

create table if not exists public.rol_permisos (
  rol_id   bigint not null references public.roles(id)   on delete cascade,
  modulo   text   not null references public.modulos(clave) on delete cascade,
  ver      boolean not null default false,
  crear    boolean not null default false,
  editar   boolean not null default false,
  eliminar boolean not null default false,
  primary key (rol_id, modulo)
);

-- Un usuario de la aplicación, colgado de la cuenta de Supabase Auth.
create table if not exists public.usuarios (
  id         uuid primary key references auth.users(id) on delete cascade,
  nombre     text,
  correo     text not null,
  rol_id     bigint references public.roles(id) on delete set null,
  activo     boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_usuarios_rol on public.usuarios (rol_id);

drop trigger if exists trg_roles_updated on public.roles;
create trigger trg_roles_updated before update on public.roles
  for each row execute function public.set_updated_at();

drop trigger if exists trg_usuarios_updated on public.usuarios;
create trigger trg_usuarios_updated before update on public.usuarios
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- catálogo
insert into public.modulos (clave, nombre, padre, orden) values
  ('dashboard',        'Dashboard',            null, 10),
  ('clientes',         'Clientes',             null, 20),
  ('clientes.cliente', 'Editar datos del cliente', 'clientes', 21),
  ('clientes.notas',   'Registrar seguimiento',   'clientes', 22),
  ('pipeline',         'Pipeline',             null, 30),
  ('calendario',       'Calendario',           null, 40),
  ('equipos',          'Equipos',              null, 50),
  ('programas',        'Programas',            null, 60),
  ('usuarios',         'Usuarios y Roles',     null, 70)
on conflict (clave) do nothing;

insert into public.roles (nombre, descripcion, es_admin) values
  ('Administrador', 'Acceso completo al sistema', true),
  ('Ventas', 'Gestión de leads y seguimiento', false)
on conflict (nombre) do nothing;

-- El administrador arranca con todo encendido.
insert into public.rol_permisos (rol_id, modulo, ver, crear, editar, eliminar)
select r.id, m.clave, true, true, true, true
from public.roles r cross join public.modulos m
where r.es_admin
on conflict (rol_id, modulo) do nothing;

-- Ventas: todo menos administrar usuarios y sin borrar nada.
insert into public.rol_permisos (rol_id, modulo, ver, crear, editar, eliminar)
select r.id, m.clave, m.clave <> 'usuarios', m.clave <> 'usuarios', m.clave <> 'usuarios', false
from public.roles r cross join public.modulos m
where r.nombre = 'Ventas'
on conflict (rol_id, modulo) do nothing;

-- Toda cuenta que ya exista en Auth entra como administrador: si no, nadie
-- podría abrir esta pantalla para repartir los permisos.
insert into public.usuarios (id, nombre, correo, rol_id)
select u.id,
       coalesce(u.raw_user_meta_data->>'full_name', split_part(u.email, '@', 1)),
       u.email,
       (select id from public.roles where es_admin limit 1)
from auth.users u
on conflict (id) do nothing;

-- ---------------------------------------------------------------- RLS
--
-- `es_admin()` es SECURITY DEFINER a propósito: las políticas de `usuarios`
-- necesitan leer `usuarios` para decidir, y una política que se consulta a sí
-- misma entra en recursión infinita. Al correr como su creador, la función
-- salta el RLS y corta el ciclo.
create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select r.es_admin
    from public.usuarios u
    join public.roles r on r.id = u.rol_id
    where u.id = (select auth.uid()) and u.activo
  ), false);
$$;

revoke execute on function public.es_admin() from anon;

alter table public.roles        enable row level security;
alter table public.modulos      enable row level security;
alter table public.rol_permisos enable row level security;
alter table public.usuarios     enable row level security;

-- Todos los que iniciaron sesión leen el catálogo: la interfaz necesita saber
-- qué puede hacer el usuario antes de dibujar el menú.
drop policy if exists lee_roles on public.roles;
create policy lee_roles on public.roles
  for select to authenticated using (true);

drop policy if exists lee_modulos on public.modulos;
create policy lee_modulos on public.modulos
  for select to authenticated using (true);

drop policy if exists lee_permisos on public.rol_permisos;
create policy lee_permisos on public.rol_permisos
  for select to authenticated using (true);

-- Cada quien ve su propia ficha; el administrador ve y edita todas.
drop policy if exists lee_usuarios on public.usuarios;
create policy lee_usuarios on public.usuarios
  for select to authenticated
  using (id = (select auth.uid()) or public.es_admin());

-- Sólo el administrador reparte roles y permisos.
drop policy if exists admin_roles on public.roles;
create policy admin_roles on public.roles
  for all to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists admin_permisos on public.rol_permisos;
create policy admin_permisos on public.rol_permisos
  for all to authenticated using (public.es_admin()) with check (public.es_admin());

drop policy if exists admin_usuarios on public.usuarios;
create policy admin_usuarios on public.usuarios
  for all to authenticated using (public.es_admin()) with check (public.es_admin());

-- Impedir que se borre o se degrade el último rol administrador.
create or replace function public.protege_admin()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    if old.es_admin then
      raise exception 'No se puede eliminar el rol administrador.';
    end if;
    return old;
  end if;

  if old.es_admin and not new.es_admin
     and not exists (select 1 from public.roles
                     where es_admin and id <> old.id) then
    raise exception 'Debe quedar al menos un rol administrador.';
  end if;
  return new;
end $$;

drop trigger if exists trg_protege_admin on public.roles;
create trigger trg_protege_admin before update or delete on public.roles
  for each row execute function public.protege_admin();
