-- Tablas de agenda: eventos de seguimiento colgados de cada oportunidad.
-- El esquema original no las contemplaba; el módulo Calendario las necesita.

-- ------------------------------------------------------------------ agenda
create table if not exists public.tipos_evento (
  id           smallint primary key,
  nombre       text not null unique,
  codigo       text not null,
  color        text not null,
  duracion_min smallint not null default 30 check (duracion_min > 0),
  orden        smallint not null default 0
);

create table if not exists public.eventos (
  id             bigint generated by default as identity primary key,
  oportunidad_id bigint not null references public.oportunidades(id) on delete cascade,
  tipo_id        smallint not null references public.tipos_evento(id),
  vendedor_id    bigint references public.vendedores(id) on delete set null,
  inicia_en      timestamptz not null,
  duracion_min   smallint not null default 30 check (duracion_min > 0),
  canal          text not null default 'Llamada'
                 check (canal in ('Presencial','Llamada','WhatsApp','Meet')),
  estado         text not null default 'Pendiente'
                 check (estado in ('Pendiente','Realizado','No se presentó','Reagendado')),
  resultado      text,
  proxima_accion text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists idx_eventos_oportunidad on public.eventos (oportunidad_id);
create index if not exists idx_eventos_inicia      on public.eventos (inicia_en);
create index if not exists idx_eventos_vendedor    on public.eventos (vendedor_id);

drop trigger if exists trg_eventos_updated on public.eventos;
create trigger trg_eventos_updated before update on public.eventos
  for each row execute function public.set_updated_at();

insert into public.tipos_evento (id, nombre, codigo, color, duracion_min, orden) values
  (0,'Llamada / videollamada','LL','#2F6FA8',30,0),
  (1,'Visita o tour al campus','TC','#B85042',60,1),
  (2,'Clase muestra o demo','CM','#8A5AA8',120,2),
  (3,'Envío de propuesta','PR','#0F6E7A',15,3),
  (4,'Seguimiento','SG','#6B665F',20,4),
  (5,'Recordatorio de pago','PG','#9C7118',15,5),
  (6,'Reactivación a 6 meses','RE','#2F6B4F',20,6)
on conflict (id) do nothing;

alter table public.tipos_evento enable row level security;
alter table public.eventos      enable row level security;

drop policy if exists auth_read_tipos_evento on public.tipos_evento;
create policy auth_read_tipos_evento on public.tipos_evento
  for select to authenticated using (true);

drop policy if exists auth_all_eventos on public.eventos;
create policy auth_all_eventos on public.eventos
  for all to authenticated using (true) with check (true);
