begin;

-- ============================================================================
-- Reacciones a los mensajes
-- ============================================================================
--
-- Lo que pidió la escuela: «le hacen falta más acciones que WhatsApp Business
-- tiene, como las reacciones a cada mensaje».
--
-- Ésta sí pasa por Meta: una reacción es un mensaje más para la API, y el
-- cliente la ve en su teléfono igual que si se la hubiéramos puesto desde el
-- celular. No es una marca interna como las de la bandeja.
--
-- ----------------------------------------------------------------------------
-- UNA POR LADO, NO UNA POR PERSONA
-- ----------------------------------------------------------------------------
--
-- WhatsApp permite una sola reacción por persona y por mensaje: poner otra
-- reemplaza la anterior, y quitarla la borra. En un chat de dos hay entonces
-- como mucho dos reacciones sobre un mensaje —la del cliente y la nuestra— y de
-- ahí sale el índice único sobre (mensaje, dirección).
--
-- «Dirección» y no «usuario» porque del lado de la escuela hay varias asesoras
-- pero un solo número de WhatsApp: para el cliente la reacción es de la
-- escuela, no de Katya. Igual se guarda quién la puso —`puesta_por`— porque
-- adentro del CRM sí importa saberlo.
--
-- ----------------------------------------------------------------------------
-- POR QUÉ UNA TABLA Y NO DOS COLUMNAS EN `mensajes`
-- ----------------------------------------------------------------------------
--
-- Dos columnas serían más baratas y alcanzarían para hoy. La tabla se paga
-- sola en dos cosas: guarda cuándo y quién —una reacción es un movimiento del
-- equipo, y las notificaciones viven de eso— y una reacción quitada se borra
-- de verdad en vez de dejar una columna en null que no distingue «nunca puso»
-- de «puso y sacó».
--
-- ----------------------------------------------------------------------------

create table if not exists public.reacciones (
  id          bigint generated by default as identity primary key,
  mensaje_id  bigint not null references public.mensajes(id) on delete cascade,
  -- 'entrante' = la puso el cliente; 'saliente' = la pusimos nosotros.
  direccion   text not null check (direccion in ('entrante', 'saliente')),
  -- El emoji tal cual. WhatsApp acepta uno solo por reacción.
  emoji       text not null,
  -- Quién la puso, de este lado. Nulo en las del cliente y en las que entran
  -- por el webhook, que no tiene sesión de nadie.
  puesta_por  uuid references auth.users(id) on delete set null,
  creado_en   timestamptz not null default now()
);

-- Una por mensaje y por lado: poner otra reemplaza, no acumula.
create unique index if not exists ux_reacciones_una_por_lado
  on public.reacciones (mensaje_id, direccion);

-- Se piden siempre por mensaje, junto con el hilo.
create index if not exists ix_reacciones_mensaje
  on public.reacciones (mensaje_id);

-- --------------------------------------------------------------------- RLS

alter table public.reacciones enable row level security;

drop policy if exists reacciones_ver    on public.reacciones;
drop policy if exists reacciones_poner  on public.reacciones;
drop policy if exists reacciones_quitar on public.reacciones;

-- Se ven las de los mensajes que uno puede ver. Es la misma condición que
-- `mensajes_ver`, escrita sobre la conversación del mensaje: sin esto, alguien
-- podría leer qué se reaccionó en un hilo que no le toca.
create policy reacciones_ver on public.reacciones
  for select to authenticated
  using (exists (
    select 1
      from public.mensajes m
      join public.conversaciones c on c.id = m.conversacion_id
     where m.id = reacciones.mensaje_id
       and (public.ve_todo()
            or c.vendedor_id is null
            or c.vendedor_id = public.mi_vendedor_id())));

/*
 * Desde el navegador sólo se ponen y se quitan las NUESTRAS.
 *
 * La del cliente la escribe el webhook, que entra con la clave de servicio y
 * se saltea RLS. Sin esta condición, cualquiera con la sesión abierta podría
 * fabricar desde el inspector una reacción del cliente —un ❤️ sobre la
 * cotización que nadie puso— y quedaría en el hilo como si fuera de él.
 */
create policy reacciones_poner on public.reacciones
  for insert to authenticated
  with check (direccion = 'saliente');

create policy reacciones_quitar on public.reacciones
  for delete to authenticated
  using (direccion = 'saliente');

-- Reemplazar una por otra se hace borrando y volviendo a poner, que es lo que
-- hace la aplicación: así no hace falta una política de update y el índice
-- único sigue siendo la única regla sobre cuántas puede haber.

commit;

-- ------------------------------------------------------------- cómo quedó

select
  case when to_regclass('public.reacciones') is not null
       then '✓ la tabla está' else '· falta' end                      as tabla,
  case when exists (
    select 1 from pg_indexes
     where schemaname = 'public' and indexname = 'ux_reacciones_una_por_lado'
  ) then '✓ una por mensaje y por lado' else '· falta' end            as una_sola,
  case when (
    select count(*) from pg_policies
     where schemaname = 'public' and tablename = 'reacciones'
  ) = 3 then '✓ con sus tres políticas' else '⚠ REVISAR' end          as permisos,
  (select count(*) from public.mensajes)                              as mensajes,
  (select count(*) from public.reacciones)                            as reacciones;
