begin;

-- Etiquetas de la bandeja.
--
-- QUÉ SON Y QUÉ NO SON, QUE ES LO QUE IMPORTA ACÁ
--
-- El CRM ya sabe en qué anda un lead: la **etapa** dice dónde está en el
-- pipeline (Primer contacto, Negociación, Cierre…) y el **estado** dice cómo
-- terminó (Ganado, Perdido). Eso vive en `oportunidades` y es de lo que salen
-- todas las métricas.
--
-- Las etiquetas NO son para repetir eso. Si existiera una etiqueta «GANADO»
-- al lado del estado Ganado, tarde o temprano una conversación diría una cosa
-- y su oportunidad la otra, y no habría manera de saber cuál vale. Por eso la
-- bandeja muestra la etapa y el estado de verdad —y deja cambiarlos— en vez de
-- copiarlos acá.
--
-- Las etiquetas son para lo que el pipeline no cubre y cambia seguido: «pidió
-- beca», «no contesta», «pago pendiente», «viene de feria». Son de la
-- conversación, no de la venta.
--
-- QUIÉN PUEDE QUÉ
--
-- Crear, cualquiera del equipo: aparecen en medio de la conversación y hacer
-- que un asesor pida permiso para anotar «no contesta» sería inútil.
-- Renombrar y borrar, sólo dirección: eso cambia lo que ya está puesto en
-- conversaciones que no son suyas.

-- ----------------------------------------------------------------- catálogo

create table if not exists public.etiquetas (
  id         bigint generated by default as identity primary key,
  nombre     text not null,
  -- Color en hexadecimal, para distinguirlas de un vistazo en la lista.
  color      text not null default '#6B665F'
             constraint etiquetas_color_valido check (color ~ '^#[0-9A-Fa-f]{6}$'),
  activa     boolean not null default true,
  creado_en  timestamptz not null default now()
);

-- Sin repetidas, y sin distinguir mayúsculas: «Pidió beca» y «pidió beca» son
-- la misma, y tenerlas dos veces partiría en dos cualquier filtro.
create unique index if not exists ux_etiquetas_nombre
  on public.etiquetas (lower(trim(nombre)));

alter table public.etiquetas enable row level security;

drop policy if exists etiquetas_leer on public.etiquetas;
create policy etiquetas_leer on public.etiquetas
  for select to authenticated using (true);

drop policy if exists etiquetas_crear on public.etiquetas;
create policy etiquetas_crear on public.etiquetas
  for insert to authenticated with check (true);

-- Cambiar el nombre o el color, y darlas de baja: sólo dirección.
drop policy if exists etiquetas_administrar on public.etiquetas;
create policy etiquetas_administrar on public.etiquetas
  for update to authenticated
  using (public.es_admin()) with check (public.es_admin());

drop policy if exists etiquetas_borrar on public.etiquetas;
create policy etiquetas_borrar on public.etiquetas
  for delete to authenticated using (public.es_admin());

-- --------------------------------------------------------------- asignación

create table if not exists public.conversacion_etiquetas (
  conversacion_id bigint not null references public.conversaciones(id) on delete cascade,
  etiqueta_id     bigint not null references public.etiquetas(id)      on delete cascade,
  puesta_por      uuid references auth.users(id) on delete set null,
  puesta_en       timestamptz not null default now(),
  primary key (conversacion_id, etiqueta_id)
);

create index if not exists ix_conv_etiquetas_etiqueta
  on public.conversacion_etiquetas (etiqueta_id);

alter table public.conversacion_etiquetas enable row level security;

-- Poner y sacar, todo el equipo: es parte de atender la conversación.
drop policy if exists conv_etiquetas_todo on public.conversacion_etiquetas;
create policy conv_etiquetas_todo on public.conversacion_etiquetas
  for all to authenticated using (true) with check (true);

-- ----------------------------------------------------------------- actividad
do $$
begin
  if exists (select 1 from pg_proc where proname = 'registrar_actividad') then
    execute 'drop trigger if exists trg_actividad_etiquetas on public.etiquetas';
    execute 'create trigger trg_actividad_etiquetas
      after insert or update or delete on public.etiquetas
      for each row execute function public.registrar_actividad(
        ''{nombre,color,activa}'', ''etiqueta'')';
  else
    raise notice 'todavía no está el registro de actividad; se omite su trigger';
  end if;
end $$;

commit;
