begin;

-- Autorizaciones de dirección general.
--
-- Sólo agrega: no toca ninguna tabla ni vista existente, así que se puede
-- correr con gente trabajando sin ningún riesgo.
--
-- Ventas pide, dirección resuelve. Que sólo un administrador pueda autorizar
-- no se deja a la interfaz: las políticas de abajo lo impiden a nivel de base,
-- así que tampoco se puede saltar llamando a la API directamente.

create table if not exists public.autorizaciones (
  id            bigint generated by default as identity primary key,
  nombre        text not null,
  descripcion   text not null default '',
  estado        text not null default 'pendiente'
                check (estado in ('pendiente', 'autorizada', 'rechazada')),
  -- Quién la pidió y cuándo.
  solicitado_por uuid references auth.users(id) on delete set null,
  solicitado_en  timestamptz not null default now(),
  -- Quién la resolvió. Nulos mientras siga pendiente.
  resuelto_por   uuid references auth.users(id) on delete set null,
  resuelto_en    timestamptz,
  -- Motivo de la decisión, sobre todo cuando se rechaza.
  comentario     text
);

create index if not exists ix_autorizaciones_estado
  on public.autorizaciones (estado, solicitado_en desc);

alter table public.autorizaciones enable row level security;

drop policy if exists autorizaciones_ver on public.autorizaciones;
drop policy if exists autorizaciones_pedir on public.autorizaciones;
drop policy if exists autorizaciones_resolver on public.autorizaciones;
drop policy if exists autorizaciones_borrar on public.autorizaciones;

-- Todo el equipo ve el tablero: saber qué está pendiente es parte del trabajo.
create policy autorizaciones_ver on public.autorizaciones
  for select to authenticated using (true);

-- Cualquiera pide, pero siempre en su propio nombre y siempre pendiente:
-- nadie se autoriza a sí mismo insertando una fila ya aprobada.
create policy autorizaciones_pedir on public.autorizaciones
  for insert to authenticated
  with check (
    estado = 'pendiente'
    and resuelto_por is null
    and resuelto_en is null
    and solicitado_por = (select auth.uid())
  );

-- Resolver es sólo de administradores. Acá está la regla de verdad.
create policy autorizaciones_resolver on public.autorizaciones
  for update to authenticated
  using (public.es_admin())
  with check (public.es_admin());

create policy autorizaciones_borrar on public.autorizaciones
  for delete to authenticated using (public.es_admin());

commit;
