begin;

-- Autorizaciones: pedirlas desde la ficha, aprobarlas desde dirección.
--
-- ------------------------------------------------------------------------
-- SOBRE LO QUE YA HABÍA
-- ------------------------------------------------------------------------
--
-- La tabla `autorizaciones` existe desde 20260731130000, con sus políticas
-- puestas: ventas pide, dirección resuelve. Lo que nunca terminó de hacerse
-- fue la pantalla, así que quedó dormida.
--
-- Este archivo no la reemplaza: le agrega lo que le falta. Rehacerla al lado
-- dejaría dos tablas con el mismo nombre en la cabeza de todos y una de las
-- dos vacía para siempre.
--
-- ------------------------------------------------------------------------
-- LO QUE LE FALTABA
-- ------------------------------------------------------------------------
--
--   EL TIPO       una autorización no se escribe de cero cada vez. Dirección
--                 arma una lista —«Descuento sobre el precio de lista», «Plan
--                 de pago fuera de lo habitual»— y el equipo elige de ahí.
--                 Cada tipo es general —sirve para cualquier lead— o
--                 específica, armada para un caso puntual.
--
--   EL LEAD       la tabla vieja no decía a quién se refería el pedido. Sin
--                 eso dirección lee «descuento» y tiene que preguntar de
--                 quién. Ahora el pedido nace desde la ficha y sabe de cuál.
--
--   QUIÉN LA VE   la política decía «todo el equipo ve el tablero». Lo pedido
--                 es que la lista sea de dirección, así que se ajusta.
--
-- ------------------------------------------------------------------------
-- POR QUÉ QUIEN PIDIÓ IGUAL VE LA SUYA
-- ------------------------------------------------------------------------
--
-- La LISTA es de dirección: el módulo se le esconde a los demás roles con las
-- casillas de Usuarios y Roles. Pero quien pidió algo tiene que poder ver en
-- la ficha si se lo aprobaron. Si no, el pedido cae en un pozo y termina
-- preguntando por WhatsApp, que es justo lo que esto viene a evitar.
--
-- Ver el estado de un pedido sobre un lead que ya tiene delante no le muestra
-- nada que no pudiera ver.
--
-- Se puede correr con gente trabajando, y dos veces.

-- ------------------------------------------------------------- los tipos

create table if not exists public.autorizaciones_tipo (
  id          bigint generated by default as identity primary key,
  nombre      text    not null unique,
  descripcion text,
  -- «general» sirve para cualquier lead; «especifica» se arma para un caso.
  clase       text    not null default 'general'
              check (clase in ('general', 'especifica')),
  activo      boolean not null default true,
  creado_en   timestamptz not null default now(),
  creado_por  uuid references auth.users(id) on delete set null
);

comment on table public.autorizaciones_tipo is
  'Qué cosas se pueden autorizar. Las crea dirección; las elige el equipo al pedir.';

alter table public.autorizaciones_tipo enable row level security;

drop policy if exists tipos_ver    on public.autorizaciones_tipo;
drop policy if exists tipos_crear  on public.autorizaciones_tipo;
drop policy if exists tipos_editar on public.autorizaciones_tipo;
drop policy if exists tipos_borrar on public.autorizaciones_tipo;

-- Verlos, todo el equipo: hay que poder elegir uno al pedir.
create policy tipos_ver on public.autorizaciones_tipo
  for select to authenticated using (true);

-- Crearlos y tocarlos, dirección.
create policy tipos_crear on public.autorizaciones_tipo
  for insert to authenticated with check (public.es_admin());
create policy tipos_editar on public.autorizaciones_tipo
  for update to authenticated using (public.es_admin()) with check (public.es_admin());
create policy tipos_borrar on public.autorizaciones_tipo
  for delete to authenticated using (public.es_admin());

-- ------------------------------------------- lo que le falta a la de pedidos

alter table public.autorizaciones
  -- De qué lead se habla. Se permite nulo: las filas viejas no lo tienen, y un
  -- pedido que no es sobre nadie en particular sigue siendo válido.
  add column if not exists oportunidad_id bigint
      references public.oportunidades(id) on delete cascade,
  add column if not exists tipo_id bigint
      references public.autorizaciones_tipo(id);

create index if not exists ix_autorizaciones_oportunidad
  on public.autorizaciones (oportunidad_id, solicitado_en desc);

-- ------------------------------------------------------------- quién ve qué

drop policy if exists autorizaciones_ver on public.autorizaciones;

/*
 * Dirección ve todas; los demás, las de los leads que ya pueden ver.
 *
 * Antes decía `using (true)`: el tablero entero para todo el mundo. Se ajusta
 * a lo pedido. `puede_ver_oportunidad` es la misma función que decide el
 * pipeline, así que no quedan dos reglas que puedan desincronizarse; y un
 * pedido sin lead lo ve sólo dirección, porque no hay ficha contra la cual
 * medir quién puede.
 */
create policy autorizaciones_ver on public.autorizaciones
  for select to authenticated
  using (
    public.es_admin()
    or (oportunidad_id is not null and public.puede_ver_oportunidad(oportunidad_id))
  );

commit;

-- --------------------------------------------------- el módulo y los tipos

begin;

-- Para que se pueda elegir quién lo ve, en Usuarios y Roles. El 69 lo pone
-- entre Notificaciones (68) y Usuarios y Roles (70).
insert into public.modulos (clave, nombre, padre, orden)
values ('autorizaciones', 'Autorizaciones', null, 69)
on conflict (clave) do update set nombre = excluded.nombre, orden = excluded.orden;

/*
 * Que el módulo aparezca sólo para dirección.
 *
 * La regla general del CRM es «sin fila guardada, se ve»: un módulo nuevo no
 * desaparece hasta que alguien lo configure. Para este hace falta lo contrario
 * —se pidió que la lista sea de dirección— así que se destilda de entrada para
 * todos los roles que no son administradores.
 *
 * Es un valor inicial, no una traba: desde Usuarios y Roles se puede volver a
 * tildar para quien haga falta.
 */
insert into public.rol_permisos (rol_id, modulo, ver)
select r.id, 'autorizaciones', false
  from public.roles r
 where not r.es_admin
on conflict (rol_id, modulo) do nothing;

/*
 * Dos tipos para arrancar, uno de cada clase.
 *
 * Sólo si la lista está vacía: una pantalla que abre sin nada no enseña para
 * qué es. Desde el módulo se agregan otros y estos se sacan de circulación.
 */
insert into public.autorizaciones_tipo (nombre, descripcion, clase)
select * from (values
  ('Descuento sobre el precio de lista',
   'Cualquier rebaja sobre el precio publicado del programa.', 'general'),
  ('Plan de pago fuera de lo habitual',
   'Más cuotas, otras fechas o una prórroga puntual.', 'especifica')
) as t(nombre, descripcion, clase)
where not exists (select 1 from public.autorizaciones_tipo);

commit;

-- Cómo quedó.
select
  (select count(*) from public.autorizaciones_tipo)               as tipos,
  (select count(*) from public.autorizaciones_tipo
    where clase = 'general')                                      as generales,
  (select count(*) from public.autorizaciones_tipo
    where clase = 'especifica')                                   as especificas,
  (select count(*) from public.autorizaciones)                    as pedidos,
  (select count(*) from public.autorizaciones where estado = 'pendiente')
                                                                  as pendientes,
  case when exists (select 1 from information_schema.columns
                     where table_schema = 'public'
                       and table_name = 'autorizaciones'
                       and column_name = 'oportunidad_id')
       then '✓ los pedidos saben de qué lead son'
       else '· falta' end                                         as lead,
  case when exists (select 1 from public.modulos where clave = 'autorizaciones')
       then '✓ el módulo se asigna por rol'
       else '· falta' end                                         as modulo;
