begin;

-- Formularios de feria: un lead que entra ya cargado.
--
-- ------------------------------------------------------------------------
-- QUÉ RESUELVE
-- ------------------------------------------------------------------------
--
-- En una feria el asesor anota los datos en papel y después alguien los pasa
-- al CRM. Entre las dos cosas se pierden teléfonos, se leen mal los correos y
-- pasan días. Con esto se llena en el momento, desde el teléfono, y el lead
-- queda cargado con su programa, su canal y su asesor.
--
-- ------------------------------------------------------------------------
-- POR QUÉ TRES TABLAS Y NO UNA COLUMNA POR PREGUNTA
-- ------------------------------------------------------------------------
--
-- Cada feria pregunta cosas distintas. Con una columna por pregunta, armar un
-- formulario nuevo sería una migración nueva, y eso lo saca de las manos de
-- quien organiza la feria. Acá las preguntas son filas.
--
-- ------------------------------------------------------------------------
-- CÓMO SE CONECTA CON EL RESTO DEL CRM
-- ------------------------------------------------------------------------
--
-- Cada pregunta puede declarar a qué campo del lead va su respuesta
-- (`mapea_a`). El nombre, el teléfono y el correo van a la ficha del cliente;
-- el área de interés va al programa. Lo que no mapea a ningún campo no se
-- pierde: se guarda tal cual en la respuesta y se escribe como nota en la
-- ficha, que es donde el asesor lo va a buscar.
--
-- Nunca se agregan columnas a `clientes` desde acá, y es a propósito: un
-- formulario que puede inventar columnas es un formulario que puede romper
-- todas las demás pantallas.
--
-- Sólo agrega tablas y un canal. Se puede correr con gente trabajando.

-- ------------------------------------------------------------ el formulario

create table if not exists public.formularios (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  -- Lo que se lee arriba, antes de la primera pregunta.
  descripcion text,
  activo      boolean not null default true,
  -- Con qué nacen los leads de este formulario. Son los datos que en una
  -- feria son iguales para todos y que nadie debería tener que tipear
  -- doscientas veces.
  canal_id      bigint references public.canales(id)      on delete set null,
  etapa_id      bigint references public.etapas(id)       on delete set null,
  estado_id     bigint references public.estados(id)      on delete set null,
  territorio_id bigint references public.territorios(id)  on delete set null,
  creado_por  uuid references auth.users(id) on delete set null,
  creado_en   timestamptz not null default now()
);

-- ------------------------------------------------------------- las preguntas

create table if not exists public.formulario_campos (
  id            bigint generated by default as identity primary key,
  formulario_id bigint not null references public.formularios(id) on delete cascade,
  orden         smallint not null,
  etiqueta      text not null,
  -- La línea chica debajo de la pregunta. Para aclarar, no para repetir.
  ayuda         text,
  tipo          text not null check (tipo in
                  ('texto','parrafo','telefono','correo','numero','opcion','opciones')),
  requerido     boolean not null default false,
  /*
   * Las opciones, cuando el tipo las lleva.
   *
   * Cada una es `{"texto": "...", "valor": 12}`. El texto es lo que lee la
   * persona; `valor` es opcional y sirve para las preguntas que alimentan un
   * catálogo: «Pastelería Internacional» puede llevar el id del Diplomado de
   * Pastelería. Así en la feria se pregunta con las palabras de la feria y el
   * lead igual cae en el programa que existe.
   */
  opciones      jsonb not null default '[]'::jsonb,
  /*
   * A qué campo del lead va la respuesta. Null = sólo a la nota.
   *
   * La lista está cerrada a propósito: son exactamente los campos que sabe
   * llenar el alta de leads. Dejarlo abierto invitaría a escribir el nombre
   * de una columna que no existe, y eso recién se notaría con la feria
   * empezada.
   */
  mapea_a       text check (mapea_a in (
                  'nombre','telefono','correo','edad',
                  'responsable_nombre','responsable_telefono','responsable_correo',
                  'producto_id','territorio_id')),
  unique (formulario_id, orden)
);

create index if not exists ix_campos_formulario
  on public.formulario_campos (formulario_id, orden);

-- ------------------------------------------------------------ lo respondido

create table if not exists public.formulario_respuestas (
  id             bigint generated by default as identity primary key,
  formulario_id  bigint not null references public.formularios(id) on delete cascade,
  -- Con `set null` y no `cascade`: si el lead se borra, la respuesta cruda
  -- sigue siendo el registro de que esa persona pasó por la feria.
  cliente_id     bigint references public.clientes(id)      on delete set null,
  oportunidad_id bigint references public.oportunidades(id) on delete set null,
  -- Lo contestado tal cual: {"id del campo": "lo que puso"}. Se guarda aunque
  -- todo haya mapeado a un campo, porque la pregunta también es un dato: en
  -- la feria siguiente sirve saber qué se preguntó y qué contestaron.
  datos          jsonb not null,
  creado_por     uuid references auth.users(id) on delete set null,
  creado_en      timestamptz not null default now()
);

create index if not exists ix_respuestas_formulario
  on public.formulario_respuestas (formulario_id, creado_en desc);

-- -------------------------------------------------------------------- RLS

alter table public.formularios           enable row level security;
alter table public.formulario_campos     enable row level security;
alter table public.formulario_respuestas enable row level security;

-- Los formularios los ve todo el equipo: hay que poder llenarlos. Armarlos y
-- cambiarlos es de administración, como los programas o los vendedores: una
-- pregunta mal editada a mitad de la feria arruina los leads de ese día.
drop policy if exists formularios_ver on public.formularios;
create policy formularios_ver on public.formularios
  for select to authenticated using (true);

drop policy if exists formularios_administrar on public.formularios;
create policy formularios_administrar on public.formularios
  for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

drop policy if exists campos_ver on public.formulario_campos;
create policy campos_ver on public.formulario_campos
  for select to authenticated using (true);

drop policy if exists campos_administrar on public.formulario_campos;
create policy campos_administrar on public.formulario_campos
  for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

-- Responder puede cualquiera del equipo: es lo que se hace en la feria.
drop policy if exists respuestas_crear on public.formulario_respuestas;
create policy respuestas_crear on public.formulario_respuestas
  for insert to authenticated
  with check (creado_por = (select auth.uid()));

-- Leerlas, en cambio, sigue la misma regla que el resto: lo propio, y todo
-- para dirección y coordinación.
drop policy if exists respuestas_ver on public.formulario_respuestas;
create policy respuestas_ver on public.formulario_respuestas
  for select to authenticated
  using (creado_por = (select auth.uid()) or public.es_admin() or public.ve_todo());

-- ------------------------------------------------------------ canal «Feria»
--
-- Sin esto los leads de feria entrarían con el canal vacío y se mezclarían
-- con los de origen desconocido, que es justo lo que un formulario de feria
-- viene a evitar: saber cuántos leads dejó cada feria.
insert into public.canales (nombre) values ('Feria')
on conflict (nombre) do nothing;

-- --------------------------------------------- el primer formulario, sembrado

do $$
declare
  f_id bigint;
begin
  if exists (select 1 from public.formularios where nombre = 'Feria — Nuevos leads') then
    raise notice 'el formulario de feria ya estaba';
    return;
  end if;

  insert into public.formularios (nombre, descripcion, canal_id, etapa_id, estado_id)
  values (
    'Feria — Nuevos leads',
    'Contanos un poco de vos y te ayudamos a encontrar el programa que va con lo que te gusta.',
    (select id from public.canales where nombre = 'Feria'),
    -- Prospectos: llenó un formulario, todavía nadie lo contactó.
    (select id from public.etapas where nombre = 'Prospectos'),
    (select id from public.estados where nombre = 'Activo')
  )
  returning id into f_id;

  insert into public.formulario_campos
    (formulario_id, orden, etiqueta, ayuda, tipo, requerido, opciones, mapea_a)
  values
    (f_id, 1, 'Nombre completo', null, 'texto', true, '[]'::jsonb, 'nombre'),
    (f_id, 2, 'Número de teléfono', 'Con ocho dígitos alcanza.', 'telefono', true,
     '[]'::jsonb, 'telefono'),
    (f_id, 3, 'Correo electrónico', null, 'correo', false, '[]'::jsonb, 'correo'),
    (f_id, 4, 'Centro educativo', null, 'texto', false, '[]'::jsonb, null),
    (f_id, 5, '¿Puedes compartirnos el número de teléfono de un responsable familiar?',
     'Si sos menor de edad, hace falta.', 'telefono', false,
     '[]'::jsonb, 'responsable_telefono'),
    -- Las opciones llevan el id del programa: se pregunta con las palabras de
    -- la feria y el lead cae igual en un programa del catálogo.
    (f_id, 6, '¿Cuál es tu área de interés principal?', null, 'opcion', true,
     (select coalesce(jsonb_agg(jsonb_build_object('texto', o.texto, 'valor', p.id)
                                order by o.orden), '[]'::jsonb)
        from (values
          (1, 'Cocina Internacional',           'Diplomado de Cocina'),
          (2, 'Pastelería Internacional',       'Diplomado de Pasteleria'),
          (3, 'Barismo y Extracción de Café',   'Diplomado de Barismo y Extracción de Café'),
          (4, 'Mixología',                      'Diplomado de Mixología'),
          (5, 'Management Gastronómico',        'Diplomado Management Gastronómico')
        ) as o(orden, texto, programa)
        left join public.productos p on p.nombre = o.programa),
     'producto_id'),
    (f_id, 7, '¿Deseas que reservemos un espacio para ti y un acompañante en una de nuestras MasterClass?',
     null, 'opcion', false,
     '[{"texto":"Sí, por favor.","valor":null},{"texto":"No estoy seguro(a).","valor":null}]'::jsonb,
     null);

  raise notice 'formulario de feria creado con 7 preguntas';
end $$;

commit;
