begin;

-- Cursos y diplomados que el cliente ya hizo.
--
-- POR QUÉ UNA TABLA Y NO COLUMNAS EN `clientes`
--
-- Una persona puede haber hecho tres cursos, o ninguno, y no se sabe de
-- antemano cuántos. Resuelto con columnas habría que inventar un tope
-- —`curso_1`, `curso_2`, `curso_3`— y el día que alguien haga el cuarto no
-- entra; además buscar «quiénes hicieron Pastelería» obligaría a mirar todas
-- las columnas una por una. Con filas no hay tope y la consulta es directa.
--
-- Cuelga del cliente y no de la oportunidad a propósito: lo que se quiere
-- saber es qué cursó esta persona, no qué se le vendió en un trato puntual. Si
-- tiene tres oportunidades abiertas, su historial es el mismo en las tres.
--
-- Sólo crea cosas nuevas. Se puede correr con gente trabajando.

create table if not exists public.cursos_realizados (
  id          bigint generated by default as identity primary key,
  cliente_id  bigint not null references public.clientes(id) on delete cascade,
  -- Del catálogo cuando el programa todavía se dicta.
  producto_id bigint references public.productos(id) on delete set null,
  -- Escrito a mano cuando no. Un curso de hace cinco años puede no estar más
  -- en el catálogo, y no poder anotarlo sería peor que anotarlo suelto.
  nombre      text,
  inicia_en   date,
  termina_en  date,
  creado_por  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now()
);

create index if not exists ix_cursos_realizados_cliente
  on public.cursos_realizados (cliente_id, inicia_en desc);

-- Para poder preguntar quiénes hicieron un programa dado.
create index if not exists ix_cursos_realizados_producto
  on public.cursos_realizados (producto_id)
  where producto_id is not null;

do $$
begin
  -- Una fila sin curso no dice nada: o se eligió del catálogo o se escribió.
  if not exists (select 1 from pg_constraint where conname = 'cursos_realizados_con_curso') then
    alter table public.cursos_realizados
      add constraint cursos_realizados_con_curso
      check (producto_id is not null or nullif(btrim(nombre), '') is not null);
  end if;

  -- Terminar antes de empezar es un error de tecleo, casi siempre el año.
  -- Las dos fechas pueden faltar: de un curso viejo a veces sólo se sabe que
  -- lo hizo, y obligar a inventar fechas ensuciaría el dato de verdad.
  if not exists (select 1 from pg_constraint where conname = 'cursos_realizados_fechas') then
    alter table public.cursos_realizados
      add constraint cursos_realizados_fechas
      check (inicia_en is null or termina_en is null or termina_en >= inicia_en);
  end if;
end $$;

alter table public.cursos_realizados enable row level security;

-- Mismo criterio que `clientes`: el equipo con sesión ve y edita. Saber qué
-- cursó alguien es parte de atenderlo, y esconderlo entre asesores obligaría a
-- preguntar por WhatsApp lo que la ficha ya sabe.
drop policy if exists cursos_realizados_equipo on public.cursos_realizados;
create policy cursos_realizados_equipo on public.cursos_realizados
  for all to authenticated using (true) with check (true);

-- ------------------------------------------------------------- actividad
--
-- Que agregar o quitar un curso quede en el registro, como el resto. La guarda
-- es porque el registro de actividad puede no estar corrido todavía.
do $$
begin
  if exists (select 1 from pg_proc where proname = 'registrar_actividad') then
    execute 'drop trigger if exists trg_actividad_cursos on public.cursos_realizados';
    execute 'create trigger trg_actividad_cursos
      after insert or delete on public.cursos_realizados
      for each row execute function public.registrar_actividad(''{}'', ''curso'')';
  else
    raise notice 'todavía no está el registro de actividad; se omite su trigger';
  end if;
end $$;

-- ----------------------------------------------------------- cambios en vivo
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public'
         and tablename = 'cursos_realizados'
     )
  then
    alter publication supabase_realtime add table public.cursos_realizados;
  end if;
end $$;

commit;
