begin;

-- ============================================================================
-- Duplicados sugeridos: la cola de revisión, su memoria y su rastro
-- ============================================================================
--
-- Lo que pidió la escuela: «si un lead entra por cualquiera de los canales,
-- que se unifique en una sola ficha; en determinado punto tiene que haber una
-- intervención de la persona encargada para analizar la información y
-- unificarla en un solo contacto».
--
-- ----------------------------------------------------------------------------
-- QUÉ FALTABA, QUE NO ERA EL RECONOCIMIENTO
-- ----------------------------------------------------------------------------
--
-- Reconocer a alguien que vuelve ya funciona y es automático: `contactos_canal`
-- guarda con qué identidad llegó por cada red, y los webhooks preguntan por ahí
-- antes de abrir nada. Quien escribió ayer por Instagram y hoy otra vez por
-- Instagram cae en su ficha sin que nadie toque nada.
--
-- Lo que no existía es el caso cruzado: la misma persona por DOS canales
-- distintos. Instagram y Messenger no entregan ni teléfono ni correo —Meta da un
-- identificador y, con suerte, un nombre de perfil—, así que no hay forma de
-- saber automáticamente que el IGSID de ayer y el número de WhatsApp de hoy son
-- la misma señora. Quedaban dos fichas y nadie se enteraba nunca.
--
-- Unificar por nombre sin que nadie mire no es una opción: dos «María González»
-- fundidas se descubren meses después, cuando una recibe la respuesta de lo que
-- preguntó la otra. Por eso esto es una COLA, no una regla automática.
--
-- ----------------------------------------------------------------------------
-- LAS TRES PIEZAS
-- ----------------------------------------------------------------------------
--
--   vw_duplicados_sugeridos   Los pares candidatos de toda la base, con la
--                             señal que los disparó y qué tan concluyente es.
--
--   duplicados_descartados    El «no es la misma persona». Sin esto la cola
--                             volvería a proponer el mismo par para siempre y
--                             la encargada dejaría de mirarla en dos semanas.
--
--   fusiones                  Quién unificó qué, cuándo y por qué señal. Una
--                             fusión no se puede deshacer sola; poder leer qué
--                             pasó es lo mínimo para arreglarlo a mano.
--
-- Se puede correr con gente trabajando, y dos veces.

-- --------------------------------------------- el «no es la misma persona»

/*
 * El par se guarda ORDENADO, y esa es toda la gracia.
 *
 * Sin el orden, (A,B) y (B,A) serían dos filas distintas: descartar el par una
 * vez no impediría que volviera a aparecer del otro lado. Con `menor < mayor`
 * hay una sola forma de escribir cada pareja, y la clave primaria hace el resto.
 */
create table if not exists public.duplicados_descartados (
  menor  bigint not null references public.clientes(id) on delete cascade,
  mayor  bigint not null references public.clientes(id) on delete cascade,
  /* Quién dijo que no. Sirve para preguntarle si alguien duda después. */
  quien  uuid references auth.users(id) on delete set null,
  cuando timestamptz not null default now(),
  primary key (menor, mayor),
  constraint duplicados_descartados_ordenado check (menor < mayor)
);

comment on table public.duplicados_descartados is
  'Pares que alguien miró y decidió que NO son la misma persona. La cola no los vuelve a proponer.';

alter table public.duplicados_descartados enable row level security;

/*
 * Lo ve y lo escribe cualquiera con sesión.
 *
 * Decidir que dos fichas no son la misma persona es trabajo de quien atiende, no
 * de dirección: la asesora que habló con las dos es la que sabe. Lo que sí está
 * restringido es FUSIONAR, que es la operación destructiva y ya pide dirección
 * —ver `exige_direccion` en la migración de fusiones—.
 */
drop policy if exists descartados_todos on public.duplicados_descartados;
create policy descartados_todos on public.duplicados_descartados
  for all to authenticated using (true) with check (true);

-- ------------------------------------------------- el rastro de las fusiones

/*
 * Los nombres de las fichas absorbidas se copian, no se referencian.
 *
 * Después de fusionar, esas fichas ya no existen: un `references` apuntaría a
 * nada y el registro diría «se absorbió al cliente 4471», que no le sirve a
 * nadie. Guardar el nombre al momento de la fusión es lo que hace que esto se
 * pueda leer dentro de seis meses.
 */
create table if not exists public.fusiones (
  id          bigint generated by default as identity primary key,
  conservado  bigint references public.clientes(id) on delete set null,
  absorbidos  bigint[] not null,
  nombres     text[]   not null,
  /* Por qué se propuso: 'correo', 'telefono', 'nombre', o varias. */
  motivos     text,
  quien       uuid references auth.users(id) on delete set null,
  cuando      timestamptz not null default now()
);

comment on table public.fusiones is
  'Quién unificó qué fichas, cuándo y por qué señal. Para poder revisar y deshacer a mano.';

create index if not exists ix_fusiones_cuando on public.fusiones (cuando desc);

alter table public.fusiones enable row level security;

/*
 * Escribirlo, cualquiera; leerlo, también.
 *
 * Es un registro de auditoría: esconderlo de quien no fusionó sería esconder
 * justamente lo que hay que poder revisar. No lleva datos sensibles —nombres de
 * fichas del propio CRM— y sin él una fusión equivocada es indistinguible de un
 * contacto que nunca existió.
 */
drop policy if exists fusiones_todos on public.fusiones;
create policy fusiones_todos on public.fusiones
  for all to authenticated using (true) with check (true);

commit;

-- ============================================================================
-- La vista de pares candidatos
-- ============================================================================

/*
 * Las mismas tres reglas que el resto del CRM, escritas en SQL.
 *
 * `lib/duplicados.ts` compara nombre, teléfono y correo normalizados, con
 * igualdad exacta. Esto tiene que decir lo mismo: si la cola propusiera pares
 * que el alta manual no considera duplicados, la encargada vería sugerencias que
 * el CRM después contradice.
 *
 *   TELÉFONO   sólo dígitos, últimos ocho. Es el largo de un número
 *              salvadoreño. Con menos de ocho no se compara, para que un «1234»
 *              suelto no empareje con media base.
 *   CORREO     minúsculas, sin espacios.
 *   NOMBRE     minúsculas, sin acentos, sin espacios de más.
 *
 * No se usa `unaccent` a propósito: es una extensión que puede no estar
 * instalada, y que la cola de duplicados dependa de eso sería un modo de fallar
 * silencioso más. `translate` hace lo mismo para las letras que aparecen en
 * nombres en castellano.
 */
create or replace view public.vw_clientes_normalizados
with (security_invoker = true) as
select
  c.id,
  c.nombre,
  c.telefono,
  c.correo,
  nullif(
    btrim(regexp_replace(
      lower(translate(coalesce(c.nombre, ''),
                      'áéíóúüñÁÉÍÓÚÜÑàèìòùÀÈÌÒÙ',
                      'aeiounAEIOUNaeiouAEIOU')),
      '\s+', ' ', 'g')),
    ''
  )                                                                as nombre_norm,
  case
    when length(regexp_replace(coalesce(c.telefono, ''), '\D', '', 'g')) >= 8
    then right(regexp_replace(coalesce(c.telefono, ''), '\D', '', 'g'), 8)
  end                                                              as tel_norm,
  nullif(lower(btrim(coalesce(c.correo, ''))), '')                 as correo_norm
from public.clientes c;

comment on view public.vw_clientes_normalizados is
  'Los clientes con sus datos normalizados igual que `lib/duplicados.ts`, para comparar.';

/**
 * Los pares de fichas que podrían ser la misma persona.
 *
 * ----------------------------------------------------------------------------
 * POR QUÉ TRES UNIONES Y NO UN CRUCE DE TODOS CONTRA TODOS
 * ----------------------------------------------------------------------------
 *
 * Con mil quinientos clientes, comparar cada uno con cada uno son más de un
 * millón de parejas, y crece con el cuadrado: al triple de clientes, nueve veces
 * el trabajo. La escuela va a seguir creciendo.
 *
 * Uniendo por el valor normalizado —los que comparten teléfono, los que
 * comparten correo, los que comparten nombre— la base usa el índice y sólo mira
 * las que de verdad coinciden. Es la diferencia entre una pantalla que abre y
 * una que tarda diez segundos el día que haya cinco mil leads.
 *
 * ----------------------------------------------------------------------------
 * `a.id < b.id` APARECE DOS VECES Y NO ES REDUNDANTE
 * ----------------------------------------------------------------------------
 *
 * En la unión evita que cada pareja salga dos veces —(A,B) y (B,A)— y que una
 * ficha se empareje consigo misma. Y deja el par en el mismo orden con el que se
 * guardan los descartes, que es lo que permite restarlos con un simple `not
 * exists`.
 */
create or replace view public.vw_duplicados_sugeridos
with (security_invoker = true) as
with pares as (
  -- Mismo correo. La señal más concluyente: es raro que dos personas compartan
  -- una casilla, y cuando pasa suele ser una pareja o una empresa, que es
  -- justamente algo que conviene que alguien mire.
  select a.id as menor, b.id as mayor, 'correo'::text as motivo
    from public.vw_clientes_normalizados a
    join public.vw_clientes_normalizados b
      on b.correo_norm = a.correo_norm and a.id < b.id
   where a.correo_norm is not null

  union all

  -- Mismo teléfono. Casi tan concluyente como el correo.
  select a.id, b.id, 'telefono'
    from public.vw_clientes_normalizados a
    join public.vw_clientes_normalizados b
      on b.tel_norm = a.tel_norm and a.id < b.id
   where a.tel_norm is not null

  union all

  /*
   * Mismo nombre. La señal débil, y la que NUNCA se unifica sola.
   *
   * Se deja entrar igual porque es la única que existe cuando alguien llegó por
   * Instagram y por WhatsApp: Meta no da teléfono ni correo. Sin esta unión, el
   * caso que la escuela vino a resolver no aparecería nunca en la cola.
   */
  select a.id, b.id, 'nombre'
    from public.vw_clientes_normalizados a
    join public.vw_clientes_normalizados b
      on b.nombre_norm = a.nombre_norm and a.id < b.id
   where a.nombre_norm is not null
),
juntos as (
  select
    menor,
    mayor,
    array_agg(distinct motivo order by motivo) as motivos,
    /*
     * El peso, con los mismos números que `lib/duplicados.ts`.
     *
     * Correo 3, teléfono 2, nombre 1, y se suman: un par que coincide en correo
     * Y teléfono pesa 5 y va primero. Quien revisa ve arriba lo que puede
     * resolver de un vistazo y abajo lo que hay que pensar.
     */
    sum(case motivo when 'correo' then 3 when 'telefono' then 2 else 1 end) as peso
  from pares
  group by menor, mayor
)
select
  j.menor,
  j.mayor,
  j.motivos,
  j.peso,
  /*
   * Cuándo escribió cada uno por última vez.
   *
   * Es lo que hace decidible un par de nombres iguales: si una ficha tiene un
   * mensaje de esta semana y la otra uno de hace dos años, casi seguro son dos
   * personas. Si las dos escribieron el mismo día por canales distintos, casi
   * seguro son la misma.
   */
  (select max(v.ultimo_mensaje_en) from public.conversaciones v
    where v.cliente_id = j.menor)                            as ultimo_menor,
  (select max(v.ultimo_mensaje_en) from public.conversaciones v
    where v.cliente_id = j.mayor)                            as ultimo_mayor,
  -- Por qué canales llegó cada uno. Dos canales distintos es la firma del caso
  -- que esto vino a resolver.
  (select string_agg(ca.nombre, ', ' order by ca.nombre)
     from public.contactos_canal cc join public.canales ca on ca.id = cc.canal_id
    where cc.cliente_id = j.menor)                           as canales_menor,
  (select string_agg(ca.nombre, ', ' order by ca.nombre)
     from public.contactos_canal cc join public.canales ca on ca.id = cc.canal_id
    where cc.cliente_id = j.mayor)                           as canales_mayor
from juntos j
where not exists (
  select 1 from public.duplicados_descartados d
   where d.menor = j.menor and d.mayor = j.mayor
);

comment on view public.vw_duplicados_sugeridos is
  'Pares de fichas que podrían ser la misma persona, sin los que ya se descartaron. Ordenar por `peso` desc.';

-- ------------------------------------------------------------- cómo quedó

select
  case when to_regclass('public.duplicados_descartados') is not null
       then '✓ la memoria de los descartes' else '⚠ falta' end          as descartes,
  case when to_regclass('public.fusiones') is not null
       then '✓ el rastro de las fusiones' else '⚠ falta' end            as rastro,
  case when to_regclass('public.vw_duplicados_sugeridos') is not null
       then '✓ la cola de revisión' else '⚠ falta' end                  as cola,
  (select count(*) from public.vw_duplicados_sugeridos)                 as pares_sugeridos,
  (select count(*) from public.vw_duplicados_sugeridos where peso >= 2) as de_esos_concluyentes;
