-- Las cuentas de Meta que el CRM tiene conectadas.
--
-- ============================================================================
-- ESTA TABLA YA EXISTE EN PRODUCCIÓN
-- ============================================================================
--
-- Se creó a mano en Supabase, sin pasar por acá, y eso tuvo dos consecuencias:
-- el repositorio no sabía que existía —así que nadie podía leer su forma sin
-- entrar al panel— y el banco de pruebas no la tenía, así que lo que la use no
-- se podía probar.
--
-- Todo lo de abajo es `if not exists` o `drop … if exists` justamente por eso:
-- CORRERLO EN PRODUCCIÓN NO CAMBIA NADA. Está escrito para el banco y para
-- dejar la forma anotada donde se lee el código.
--
-- ============================================================================
-- PARA QUÉ SIRVE
-- ============================================================================
--
-- Hasta ahora, la cuenta con la que el CRM habla por Instagram y Messenger
-- salía de las variables del servidor. Eso alcanza para UNA cuenta puesta a
-- mano, y deja de alcanzar en dos casos:
--
--   LA REVISIÓN DE META   Para aprobar los mensajes de Instagram, Meta manda a
--                         una persona a probar el producto, y esa persona
--                         conecta SU PROPIA cuenta. El CRM tiene que poder
--                         contestarle con el token de ella, no con el de la
--                         escuela.
--
--   ROTAR UN TOKEN        Con esto es apretar un botón, no editar Netlify y
--                         volver a desplegar.
--
-- Las variables siguen siendo el piso: sin filas acá, el CRM se comporta
-- exactamente como antes.

create table if not exists public.canal_credenciales (
  id                      bigint generated by default as identity primary key,
  -- A qué canal del catálogo corresponde: 1 Instagram, 10 Messenger.
  canal_id                bigint references public.canales(id) on delete set null,
  -- La Página de Facebook, que es a quien Meta le reconoce la mensajería.
  -- También para Instagram: con Facebook Login, los mensajes de Instagram
  -- salen por el token y el id de la PÁGINA.
  page_id                 text not null,
  page_nombre             text,
  -- La cuenta de Instagram ligada a esa Página, cuando la hay.
  ig_business_account_id  text,
  -- El token de la Página. Nunca sale del servidor: lo lee la llave de
  -- servicio y las pantallas reciben todo menos esta columna.
  access_token            text not null,
  token_tipo              text,
  activo                  boolean not null default true,
  autorizado_por          uuid references auth.users(id) on delete set null,
  creado_en               timestamptz not null default now(),
  actualizado_en          timestamptz not null default now()
);

-- Reconectar la misma Página ACTUALIZA en vez de duplicar. Sin esto quedarían
-- dos filas activas para la misma cuenta y cuál gana sería cuestión de suerte,
-- que es la peor forma de elegir un token.
create unique index if not exists ux_canal_credenciales_pagina
  on public.canal_credenciales (canal_id, page_id);

-- Por acá se busca al contestar: la cuenta activa de un canal.
create index if not exists ix_canal_credenciales_activas
  on public.canal_credenciales (canal_id, activo);

comment on table public.canal_credenciales is
  'Cuentas de Meta conectadas desde el CRM. El token se lee sólo con la llave de servicio.';

-- ---------------------------------------------------------------- permisos
--
-- Esta tabla guarda tokens, así que la regla es la más estricta que hay en el
-- CRM: NADIE la lee con su sesión, ni siquiera dirección.
--
-- La pantalla de Canales no la consulta directamente: pide los datos a una
-- acción del servidor que devuelve todo MENOS el token. Así, aunque alguien se
-- equivoque mañana y haga un `select *` desde el navegador, no hay nada que
-- filtrar: la política no deja leer ni una fila.
--
-- La llave de servicio pasa por encima de RLS por definición, y es la que usan
-- el webhook y el envío.

alter table public.canal_credenciales enable row level security;

drop policy if exists canal_credenciales_nadie_lee on public.canal_credenciales;
create policy canal_credenciales_nadie_lee
  on public.canal_credenciales
  for all
  to authenticated
  using (false)
  with check (false);

revoke all on public.canal_credenciales from anon;
revoke all on public.canal_credenciales from authenticated;
