begin;

-- Registro de actividad: qué hizo cada quien.
--
-- POR QUÉ CON TRIGGERS Y NO ESCRIBIENDO DESDE EL CÓDIGO
--
-- A la base se le escribe desde varios lados: la ficha, el alta, la
-- importación de bases, la API que usa n8n y el webhook de WhatsApp. Si cada
-- uno tuviera que acordarse de dejar su rastro, el registro estaría completo
-- exactamente hasta el día que alguien agregue un camino nuevo y se olvide, y
-- desde afuera un registro incompleto se ve igual que uno completo. Con
-- triggers no hay forma de escribir sin quedar anotado.
--
-- QUÉ SE GUARDA
--
-- Los ids tal como están, no frases armadas. «Cambió la etapa a 3» se redacta
-- en la pantalla, que ya tiene los catálogos cargados y sabe que 3 es
-- «Negociación». Guardar la frase acá obligaría a hacer joins dentro del
-- trigger —más lento en cada escritura— y a migrar el texto viejo cada vez que
-- alguien renombre una etapa.
--
-- QUIÉN LO VE
--
-- Ventas ve lo suyo; dirección ve todo. Lo decide la política de la base, no
-- la pantalla.
--
-- Sólo agrega cosas nuevas. Se puede correr con gente trabajando.

create table if not exists public.actividad (
  id             bigint generated by default as identity primary key,
  -- 'oportunidad' | 'cliente' | 'nota' | 'adjunto'
  entidad        text   not null,
  -- 'creo' | 'edito' | 'borro'
  accion         text   not null,
  entidad_id     bigint,
  -- Para poder abrir la ficha desde el aviso. Nulo cuando no cuelga de una.
  oportunidad_id bigint,
  -- {"etapa_id": {"antes": 2, "despues": 3}} — sólo en las ediciones.
  campos         jsonb,
  -- Nulo cuando escribió una integración con la llave de servicio: n8n o el
  -- webhook de WhatsApp no son una persona, y decir que fue alguien sería peor
  -- que no decir nada.
  actor_id       uuid   references auth.users(id) on delete set null,
  creado_en      timestamptz not null default now()
);

-- El panel siempre pide lo último; el índice va en ese orden.
create index if not exists ix_actividad_reciente on public.actividad (creado_en desc);
create index if not exists ix_actividad_actor    on public.actividad (actor_id, creado_en desc);
create index if not exists ix_actividad_op       on public.actividad (oportunidad_id, creado_en desc);

-- --------------------------------------------------------------- el trigger

/**
 * Deja el rastro de lo que acaba de pasar.
 *
 * Las columnas que interesan se pasan como argumento del trigger, una por
 * tabla. Anotar todas daría avisos de `updated_at`, que cambia siempre y no le
 * dice nada a nadie; el registro se volvería ilegible y nadie lo miraría.
 */
create or replace function public.registrar_actividad()
returns trigger
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  vigiladas text[] := tg_argv[0]::text[];
  columna   text;
  antes     jsonb;
  despues   jsonb;
  cambios   jsonb := '{}'::jsonb;
  fila      jsonb;
  op_id     bigint;
begin
  if tg_op = 'DELETE' then
    fila := to_jsonb(old);
  else
    fila := to_jsonb(new);
  end if;

  -- De qué oportunidad se trata. En `oportunidades` es su propio id; en las
  -- demás, la columna que la referencia.
  if tg_table_name = 'oportunidades' then
    op_id := (fila ->> 'id')::bigint;
  else
    op_id := nullif(fila ->> 'oportunidad_id', '')::bigint;
  end if;

  if tg_op = 'UPDATE' then
    foreach columna in array vigiladas loop
      antes   := to_jsonb(old) -> columna;
      despues := to_jsonb(new) -> columna;
      if antes is distinct from despues then
        cambios := cambios || jsonb_build_object(
          columna, jsonb_build_object('antes', antes, 'despues', despues)
        );
      end if;
    end loop;

    -- Nada de lo que importa cambió: no se anota. Guardar un aviso vacío por
    -- cada `updated_at` llenaría el panel de ruido.
    if cambios = '{}'::jsonb then
      return null;
    end if;
  end if;

  insert into public.actividad (entidad, accion, entidad_id, oportunidad_id, campos, actor_id)
  values (
    tg_argv[1],
    case tg_op when 'INSERT' then 'creo' when 'UPDATE' then 'edito' else 'borro' end,
    (fila ->> 'id')::bigint,
    op_id,
    case when tg_op = 'UPDATE' then cambios else null end,
    auth.uid()
  );

  return null;
end $$;

-- `after` y no `before`: si la escritura falla, no queda anotada una acción que
-- nunca ocurrió. Devolver null en un trigger `after` no altera nada.

drop trigger if exists trg_actividad_oportunidades on public.oportunidades;
create trigger trg_actividad_oportunidades
  after insert or update or delete on public.oportunidades
  for each row execute function public.registrar_actividad(
    '{etapa_id,estado_id,vendedor_id,producto_id,territorio_id,canal_id,valor_oportunidad,venta_cerrada,fecha_cierre,descuento_promocion}',
    'oportunidad'
  );

drop trigger if exists trg_actividad_clientes on public.clientes;
create trigger trg_actividad_clientes
  after insert or update or delete on public.clientes
  for each row execute function public.registrar_actividad(
    '{nombre,telefono,correo,edad,responsable_nombre,responsable_telefono,responsable_correo}',
    'cliente'
  );

-- Las notas y los adjuntos no se editan: se crean y se quitan. La lista de
-- columnas va vacía porque nunca se recorre.
drop trigger if exists trg_actividad_notas on public.oportunidad_notas;
create trigger trg_actividad_notas
  after insert or delete on public.oportunidad_notas
  for each row execute function public.registrar_actividad('{}', 'nota');

do $$
begin
  if to_regclass('public.adjuntos') is not null then
    execute 'drop trigger if exists trg_actividad_adjuntos on public.adjuntos';
    execute 'create trigger trg_actividad_adjuntos
      after insert or delete on public.adjuntos
      for each row execute function public.registrar_actividad(''{}'', ''adjunto'')';
  else
    raise notice 'todavía no existe la tabla adjuntos; se omite su trigger';
  end if;
end $$;

-- ------------------------------------------------------------------ permisos

alter table public.actividad enable row level security;

-- Ventas ve lo suyo; dirección ve todo. Es la misma regla que pidieron para el
-- panel, puesta donde no se puede saltar: aunque una pantalla futura pidiera
-- la tabla entera, la base devuelve nada más lo que corresponde.
drop policy if exists actividad_leer on public.actividad;
create policy actividad_leer on public.actividad
  for select to authenticated
  using (actor_id = (select auth.uid()) or public.es_admin());

-- No hay política de insert, update ni delete a propósito. Las filas las pone
-- el trigger, que corre como `security definer` y no pasa por acá. Sin esto,
-- alguien podría inventarse actividad ajena o borrar la propia, y un registro
-- que se puede editar no sirve para controlar nada.

-- ------------------------------------------------- hasta dónde vio cada quien
--
-- Para poder marcar cuántos avisos hay sin leer. Una fila por persona.
create table if not exists public.actividad_vista (
  usuario_id uuid primary key references auth.users(id) on delete cascade,
  visto_en   timestamptz not null default now()
);

alter table public.actividad_vista enable row level security;

drop policy if exists actividad_vista_propia on public.actividad_vista;
create policy actividad_vista_propia on public.actividad_vista
  for all to authenticated
  using (usuario_id = (select auth.uid()))
  with check (usuario_id = (select auth.uid()));

-- ----------------------------------------------------------- cambios en vivo
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'actividad'
     )
  then
    alter publication supabase_realtime add table public.actividad;
  end if;
end $$;

commit;
