begin;

-- Bandeja de WhatsApp.
--
-- Sólo agrega tablas: no toca ninguna existente, así que se puede correr con
-- gente trabajando.
--
-- La decisión de fondo: un mensaje entrante NO crea un cliente. Cae en la
-- bandeja y ahí queda hasta que alguien de ventas aprieta «Crear lead». Si
-- cada número que escribe entrara solo a `clientes`, la base se llenaría de
-- números equivocados, proveedores y spam, y todo el trabajo contra
-- duplicados no serviría de nada. Por eso `cliente_id` acepta nulos: una
-- conversación sin dueño es el estado normal al principio, no un error.

-- ------------------------------------------------------------ conversaciones
create table if not exists public.conversaciones (
  id                bigint generated by default as identity primary key,
  -- El `wa_id` de Meta: sólo dígitos, con código de país y sin signos. Único
  -- porque una persona es una conversación, por más veces que escriba.
  telefono          text not null unique,
  -- Cómo se llama en su propio WhatsApp. Es lo único que se sabe de alguien
  -- que todavía no es cliente, y sirve para reconocerlo en la lista.
  nombre_perfil     text,
  canal             text not null default 'whatsapp',
  -- Nulo mientras nadie la haya convertido en lead.
  cliente_id        bigint references public.clientes(id) on delete set null,
  ultimo_mensaje_en timestamptz not null default now(),
  ultimo_texto      text,
  sin_leer          integer not null default 0,
  archivada         boolean not null default false,
  created_at        timestamptz not null default now()
);

-- La bandeja se ordena por actividad reciente, y las archivadas no se ven.
create index if not exists ix_conversaciones_actividad
  on public.conversaciones (archivada, ultimo_mensaje_en desc);
create index if not exists ix_conversaciones_cliente
  on public.conversaciones (cliente_id);

-- ------------------------------------------------------------------ mensajes
create table if not exists public.mensajes (
  id              bigint generated by default as identity primary key,
  conversacion_id bigint not null references public.conversaciones(id) on delete cascade,
  -- El id que le pone Meta. Único a propósito: Meta reintenta el webhook
  -- cuando no recibe un 200 a tiempo, y sin esto el mismo mensaje entraría
  -- dos o tres veces. Con la restricción, el reintento choca y se ignora.
  wa_id           text unique,
  direccion       text not null check (direccion in ('entrante', 'saliente')),
  tipo            text not null default 'text',
  texto           text,
  -- El JSON crudo de Meta. Hoy sólo se usa el texto, pero cuando lleguen
  -- fotos, audios o ubicaciones el dato ya va a estar guardado en vez de
  -- haberse perdido.
  payload         jsonb,
  -- Sólo para los salientes: enviado / entregado / leido / fallido.
  estado          text,
  error           text,
  enviado_por     uuid references auth.users(id) on delete set null,
  creado_en       timestamptz not null default now()
);

create index if not exists ix_mensajes_conversacion
  on public.mensajes (conversacion_id, creado_en);

-- --------------------------------------------------------------------- RLS
alter table public.conversaciones enable row level security;
alter table public.mensajes       enable row level security;

drop policy if exists conversaciones_ver     on public.conversaciones;
drop policy if exists conversaciones_editar  on public.conversaciones;
drop policy if exists mensajes_ver           on public.mensajes;
drop policy if exists mensajes_enviar        on public.mensajes;

-- Toda la bandeja es del equipo: quién atiende qué se coordina hablando, no
-- escondiendo conversaciones.
create policy conversaciones_ver on public.conversaciones
  for select to authenticated using (true);

-- Vincular con un cliente, marcar leído y archivar. El webhook no pasa por
-- acá: entra con la clave de servicio, que se salta RLS.
create policy conversaciones_editar on public.conversaciones
  for update to authenticated using (true) with check (true);

create policy mensajes_ver on public.mensajes
  for select to authenticated using (true);

-- Se puede insertar sólo lo que uno mismo manda. Un entrante lo escribe el
-- webhook, y nadie puede fabricar uno desde el navegador para simular que un
-- cliente dijo algo que no dijo.
create policy mensajes_enviar on public.mensajes
  for insert to authenticated
  with check (direccion = 'saliente' and enviado_por = (select auth.uid()));

-- ------------------------------------------------ contador de no leídos
--
-- Se suma en la base y no en el servidor. Dos mensajes que entran a la vez
-- leerían los dos el mismo valor viejo y guardarían el mismo número, así que
-- uno de los dos se perdería: la bandeja diría «1 sin leer» habiendo dos.
-- Con `sin_leer + 1` dentro de un update, Postgres serializa las dos.
--
-- Es SECURITY DEFINER porque la llama el webhook con la clave de servicio,
-- que ya se salta RLS; el efecto es el mismo y así la firma queda explícita.
create or replace function public.marcar_mensaje_entrante(
  p_conversacion bigint,
  p_texto        text,
  p_cuando       timestamptz
) returns void
language sql
security definer
set search_path = public
as $$
  update public.conversaciones
     set sin_leer          = sin_leer + 1,
         ultimo_texto      = p_texto,
         -- Nunca hacia atrás: un webhook reintentado fuera de orden no debe
         -- mover la conversación a un lugar más viejo de la lista.
         ultimo_mensaje_en = greatest(ultimo_mensaje_en, p_cuando),
         archivada         = false
   where id = p_conversacion;
$$;

-- ------------------------------------------------------- cambios en vivo
-- La bandeja no sirve si hay que recargar para ver un mensaje nuevo.
do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'mensajes'
  ) then
    alter publication supabase_realtime add table public.mensajes;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'conversaciones'
  ) then
    alter publication supabase_realtime add table public.conversaciones;
  end if;
end $$;

commit;
