begin;

-- Documentos adjuntos de una oportunidad.
--
-- Los asesores reciben del cliente su documentación —DUI, comprobantes— y
-- capturas de las transferencias. Hoy eso vive en el WhatsApp de cada quien:
-- si la persona se va, o cambia de teléfono, el respaldo del pago se va con
-- ella. Acá queda colgado de la oportunidad, donde lo ve el equipo.
--
-- Los archivos NO van en la base: van en el almacenamiento de Supabase, y en
-- esta tabla queda la ficha —dónde está, cómo se llamaba, quién lo subió—.
-- Guardar una captura de 3 MB dentro de una fila haría lenta cualquier
-- consulta que ni siquiera la esté pidiendo.
--
-- Sólo crea cosas nuevas. No toca ninguna tabla existente, así que se puede
-- correr con gente trabajando.

-- ------------------------------------------------------------------ el balde
--
-- Privado, y esto no es un detalle: adentro hay documentos de identidad y
-- comprobantes bancarios. Un balde público sería una URL que cualquiera con
-- el enlace abre, para siempre. Al ser privado, cada archivo se sirve con un
-- enlace firmado que caduca, y sólo se lo puede pedir alguien con sesión.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'adjuntos',
  'adjuntos',
  false,
  15 * 1024 * 1024,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]
)
on conflict (id) do update
  set public             = false,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- --------------------------------------------------------------- la ficha
create table if not exists public.adjuntos (
  id             bigint generated by default as identity primary key,
  oportunidad_id bigint not null references public.oportunidades(id) on delete cascade,
  -- Dónde quedó dentro del balde. Es la llave para pedirlo y para borrarlo.
  ruta           text not null unique,
  -- Cómo se llamaba el archivo en la computadora de quien lo subió. La ruta
  -- no lo conserva: se arma con un identificador al azar a propósito, porque
  -- «comprobante (1).png» y los acentos rompen las llaves del almacenamiento.
  nombre         text not null,
  tipo_mime      text,
  tamano_bytes   bigint,
  subido_por     uuid references auth.users(id) on delete set null,
  created_at     timestamptz not null default now()
);

create index if not exists idx_adjuntos_oportunidad
  on public.adjuntos (oportunidad_id, created_at desc);

alter table public.adjuntos enable row level security;

-- Ver y subir: cualquiera con sesión, igual que el resto del CRM. Un asesor
-- necesita ver el comprobante que subió su compañera cuando le pasan un
-- cliente.
drop policy if exists adjuntos_leer on public.adjuntos;
create policy adjuntos_leer on public.adjuntos
  for select to authenticated using (true);

drop policy if exists adjuntos_subir on public.adjuntos;
create policy adjuntos_subir on public.adjuntos
  for insert to authenticated
  with check (subido_por = (select auth.uid()));

-- Borrar es otra cosa. Un comprobante de pago es el respaldo de que alguien
-- pagó: se lo puede quitar quien lo subió —porque se equivocó de archivo, que
-- pasa— o un administrador. Nadie más borra el respaldo de otro.
drop policy if exists adjuntos_borrar on public.adjuntos;
create policy adjuntos_borrar on public.adjuntos
  for delete to authenticated
  using (subido_por = (select auth.uid()) or public.es_admin());

-- No hay política de update: un adjunto no se edita. Si el archivo estaba
-- mal, se quita y se sube el bueno, y así la bitácora muestra las dos cosas.

-- ------------------------------------------------- permisos del almacenamiento
--
-- Las mismas reglas, pero sobre los archivos. Sin esto la fila se crearía y el
-- archivo no, o al revés.
--
-- `storage.objects` ya viene con RLS prendido de fábrica en Supabase.
drop policy if exists adjuntos_ver_archivo on storage.objects;
create policy adjuntos_ver_archivo on storage.objects
  for select to authenticated
  using (bucket_id = 'adjuntos');

drop policy if exists adjuntos_subir_archivo on storage.objects;
create policy adjuntos_subir_archivo on storage.objects
  for insert to authenticated
  with check (bucket_id = 'adjuntos' and owner = (select auth.uid()));

drop policy if exists adjuntos_borrar_archivo on storage.objects;
create policy adjuntos_borrar_archivo on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'adjuntos'
    and (owner = (select auth.uid()) or public.es_admin())
  );

-- ----------------------------------------------------------- cambios en vivo
--
-- Para que un adjunto aparezca en la pantalla de quien tiene la ficha abierta
-- sin que tenga que recargar. La guarda es porque la publicación puede no
-- existir si esta migración se corre antes que la de cambios en vivo.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'adjuntos'
     )
  then
    alter publication supabase_realtime add table public.adjuntos;
  end if;
end $$;

commit;
