-- =====================================================================
-- CRM Les Arts Culinaires — Esquema para Supabase (PostgreSQL)
-- Ejecutar COMPLETO en: Supabase → SQL Editor → New query → Run
-- Luego importar los CSV en el orden 01..09 y ejecutar 02_post_import.sql
-- =====================================================================

-- ---------------------------------------------------------------- catálogos
create table if not exists public.vendedores (
  id          bigint generated by default as identity primary key,
  nombre      text not null unique,
  correo      text unique,
  activo      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.territorios (
  id     bigint generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists public.canales (
  id     bigint generated by default as identity primary key,
  nombre text not null unique          -- Facebook, Instagram, WhatsApp, Referido...
);

create table if not exists public.productos (
  id         bigint generated by default as identity primary key,
  nombre     text not null unique,
  categoria  text not null default 'Otro'
             check (categoria in ('Diplomado','Curso corto','Certificación','Otro')),
  precio     numeric(12,2),            -- por llenar: precio de lista
  activo     boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.etapas (          -- pipeline
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  orden  smallint not null unique
);

create table if not exists public.estados (
  id       bigint generated by default as identity primary key,
  nombre   text not null unique,
  es_final boolean not null default false
);

-- ---------------------------------------------------------------- clientes
create table if not exists public.clientes (
  id                  bigint generated by default as identity primary key,
  nombre              text not null,
  telefono            text,
  telefono_secundario text,
  correo              text,
  territorio_id       bigint references public.territorios(id) on delete set null,
  activo              boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index if not exists idx_clientes_correo   on public.clientes (lower(correo));
create index if not exists idx_clientes_telefono on public.clientes (telefono);
create index if not exists idx_clientes_nombre   on public.clientes using gin (to_tsvector('spanish', nombre));

-- ---------------------------------------------------------------- oportunidades
create table if not exists public.oportunidades (
  id                  bigint generated by default as identity primary key,
  codigo              text unique,      -- CRM-0001 (código heredado del Excel)
  cliente_id          bigint not null references public.clientes(id)    on delete cascade,
  vendedor_id         bigint references public.vendedores(id)           on delete set null,
  producto_id         bigint references public.productos(id)            on delete set null,
  territorio_id       bigint references public.territorios(id)          on delete set null,
  canal_id            bigint references public.canales(id)              on delete set null,
  etapa_id            bigint references public.etapas(id)               on delete set null,
  estado_id           bigint references public.estados(id)              on delete set null,
  fecha_registro      date not null default current_date,
  fecha_cierre        date,
  valor_oportunidad   numeric(12,2) check (valor_oportunidad >= 0),
  venta_cerrada       numeric(12,2) check (venta_cerrada >= 0),
  descuento_promocion text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index if not exists idx_op_vendedor on public.oportunidades (vendedor_id);
create index if not exists idx_op_etapa    on public.oportunidades (etapa_id);
create index if not exists idx_op_estado   on public.oportunidades (estado_id);
create index if not exists idx_op_fecha    on public.oportunidades (fecha_registro);
create index if not exists idx_op_producto on public.oportunidades (producto_id);

-- ---------------------------------------------------------------- bitácora
create table if not exists public.oportunidad_notas (
  id             bigint generated by default as identity primary key,
  oportunidad_id bigint not null references public.oportunidades(id) on delete cascade,
  nota           text not null,
  origen         text not null default 'comentario',  -- de qué columna del Excel vino
  autor_id       uuid references auth.users(id) on delete set null,
  created_at     timestamptz not null default now()
);
create index if not exists idx_notas_op on public.oportunidad_notas (oportunidad_id);

-- ---------------------------------------------------------------- updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_clientes_updated on public.clientes;
create trigger trg_clientes_updated before update on public.clientes
  for each row execute function public.set_updated_at();

drop trigger if exists trg_oportunidades_updated on public.oportunidades;
create trigger trg_oportunidades_updated before update on public.oportunidades
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- vistas dashboard
create or replace view public.vw_pipeline as
select o.id, o.codigo, o.fecha_registro,
       date_trunc('month', o.fecha_registro)::date as mes,
       c.nombre as cliente, c.telefono, c.correo,
       v.nombre as vendedor, p.nombre as producto, p.categoria,
       t.nombre as territorio, ca.nombre as canal,
       e.nombre as etapa, e.orden as etapa_orden,
       s.nombre as estado, s.es_final,
       o.valor_oportunidad, o.venta_cerrada, o.descuento_promocion
from public.oportunidades o
join public.clientes c   on c.id = o.cliente_id
left join public.vendedores  v  on v.id  = o.vendedor_id
left join public.productos   p  on p.id  = o.producto_id
left join public.territorios t  on t.id  = o.territorio_id
left join public.canales     ca on ca.id = o.canal_id
left join public.etapas      e  on e.id  = o.etapa_id
left join public.estados     s  on s.id  = o.estado_id;

create or replace view public.vw_kpi_vendedor as
select v.nombre as vendedor,
       count(*)                                              as total_oportunidades,
       count(*) filter (where s.nombre = 'Ganado')            as ganadas,
       round(100.0 * count(*) filter (where s.nombre = 'Ganado') / nullif(count(*),0), 1) as tasa_cierre_pct,
       coalesce(sum(o.venta_cerrada), 0)                      as monto_cerrado,
       coalesce(sum(o.valor_oportunidad), 0)                  as monto_en_pipeline
from public.oportunidades o
left join public.vendedores v on v.id = o.vendedor_id
left join public.estados    s on s.id = o.estado_id
group by v.nombre;

create or replace view public.vw_embudo as
select e.nombre as etapa, e.orden, count(o.id) as oportunidades,
       coalesce(sum(o.valor_oportunidad), 0) as valor
from public.etapas e
left join public.oportunidades o on o.etapa_id = e.id
group by e.nombre, e.orden
order by e.orden;

-- ---------------------------------------------------------------- RLS
-- Supabase expone las tablas vía API: sin RLS quedarían públicas.
alter table public.vendedores        enable row level security;
alter table public.territorios       enable row level security;
alter table public.canales           enable row level security;
alter table public.productos         enable row level security;
alter table public.etapas            enable row level security;
alter table public.estados           enable row level security;
alter table public.clientes          enable row level security;
alter table public.oportunidades     enable row level security;
alter table public.oportunidad_notas enable row level security;

-- Política inicial: cualquier usuario autenticado puede leer y escribir.
-- Endurecer después (ej. que cada vendedor vea solo sus oportunidades).
do $$
declare t text;
begin
  foreach t in array array['vendedores','territorios','canales','productos','etapas','estados',
                           'clientes','oportunidades','oportunidad_notas']
  loop
    execute format('drop policy if exists %I on public.%I', 'auth_all_'||t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (true) with check (true)',
      'auth_all_'||t, t);
  end loop;
end $$;
