begin;

-- ============================================================================
-- Envíos masivos por WhatsApp
-- ============================================================================
--
-- Lo que pidió la escuela: «poder seleccionar a los leads o clientes para
-- escribirles grupalmente y enviar mensajes masivos con plantilla aprobada por
-- Meta […] un total análisis y métricas de quiénes contestaron a ese mensaje
-- masivo, y que no vaya a generar algún conflicto con Meta como bloquear la
-- cuenta».
--
-- Esa última frase es la que gobierna todo lo de abajo. Un envío masivo mal
-- hecho no falla: funciona, y a las dos semanas el número de la escuela deja
-- de poder mandar nada. Por eso el diseño no es «una lista de teléfonos y un
-- botón», sino una tabla por destinatario con su estado, para poder frenar,
-- reanudar, no mandar dos veces, y saber exactamente qué pasó con cada uno.
--
-- ----------------------------------------------------------------------------
-- LAS TRES COSAS QUE PROTEGEN LA CUENTA
-- ----------------------------------------------------------------------------
--
--   1. UNA FILA POR DESTINATARIO, CON ESTADO
--
--      Sin esto, un envío que se corta a la mitad —se cierra el navegador, se
--      cae la conexión— no se puede reanudar sin volver a mandarle a los que
--      ya recibieron. Recibir el mismo mensaje dos veces es la razón número
--      uno por la que alguien bloquea un número, y los bloqueos son lo que
--      baja la calificación de calidad que Meta le pone a la cuenta.
--
--   2. «NO MOLESTAR», EN LA FICHA
--
--      Alguien que pidió que no le escriban más no puede volver a entrar en
--      una lista nunca, por más que alguien lo seleccione a mano. Es una
--      columna del contacto y no una etiqueta: las etiquetas se quitan sin
--      querer.
--
--   3. NO REPETIRLE A LA MISMA PERSONA
--
--      El índice único (envío, cliente) impide que la misma persona entre dos
--      veces en el mismo envío, que es lo que pasa cuando alguien selecciona
--      leads y una persona tiene tres.
--
-- ----------------------------------------------------------------------------
-- LO QUE ESTA TABLA NO DECIDE
-- ----------------------------------------------------------------------------
--
-- El ritmo de envío y el tope diario. Eso vive en la aplicación, porque
-- depende del nivel de mensajería que Meta le tenga puesto al número —1.000,
-- 10.000 o 100.000 destinatarios por día— y ese número cambia solo.
--
-- Se puede correr con gente trabajando, y dos veces.

-- ------------------------------------------------------------ no molestar

alter table public.clientes
  -- Pidió que no le escriban. Nunca entra en un envío masivo, lo seleccione
  -- quien lo seleccione. No impide contestarle si escribe: eso es atenderlo.
  add column if not exists no_molestar boolean not null default false;

comment on column public.clientes.no_molestar is
  'Pidió no recibir envíos masivos. Se respeta siempre, aunque alguien lo seleccione.';

-- ---------------------------------------------------------------- el envío

create table if not exists public.envios (
  id                bigint generated by default as identity primary key,
  -- Cómo se llama la campaña para quien la mira después: «Diplomado agosto».
  nombre            text not null,
  -- La plantilla aprobada. Se guarda también su texto y su nombre, no sólo el
  -- id: una plantilla se puede borrar o cambiar en Meta, y el historial de lo
  -- que se mandó no puede quedar diciendo «plantilla 47».
  plantilla_id      text,
  plantilla_nombre  text,
  idioma            text,
  cuerpo            text,
  -- Lo que se escribió en los huecos, en orden.
  valores           jsonb not null default '[]'::jsonb,
  -- borrador → enviando → terminado. «cancelado» lo pone una persona.
  estado            text not null default 'borrador'
                    check (estado in ('borrador', 'enviando', 'terminado', 'cancelado')),
  creado_por        uuid references auth.users(id) on delete set null,
  creado_en         timestamptz not null default now(),
  empezado_en       timestamptz,
  terminado_en      timestamptz
);

create index if not exists ix_envios_recientes
  on public.envios (creado_en desc);

-- ---------------------------------------------------------- los destinatarios

create table if not exists public.envio_destinatarios (
  id             bigint generated by default as identity primary key,
  envio_id       bigint not null references public.envios(id) on delete cascade,
  cliente_id     bigint not null references public.clientes(id) on delete cascade,
  -- El lead desde el que se lo eligió. Sirve para volver a la ficha desde las
  -- métricas; se pone en null si el lead se borra, sin perder el destinatario.
  oportunidad_id bigint references public.oportunidades(id) on delete set null,
  -- Copiados a propósito: si el contacto cambia de teléfono mañana, el
  -- historial tiene que seguir diciendo a dónde se mandó.
  telefono       text not null,
  nombre         text,
  /*
   * pendiente  todavía no salió
   * enviado    Meta lo aceptó
   * entregado  llegó al teléfono
   * leido      lo abrió
   * respondio  contestó — es la métrica que pidió la escuela
   * fallido    Meta lo rechazó; `motivo` dice por qué
   * omitido    no se le mandó a propósito; `motivo` dice por qué
   */
  estado         text not null default 'pendiente'
                 check (estado in ('pendiente', 'enviado', 'entregado', 'leido',
                                   'respondio', 'fallido', 'omitido')),
  motivo         text,
  -- El id que le puso Meta. Es la llave con la que el webhook cruza los acuses
  -- de entrega y de lectura.
  wa_id          text,
  enviado_en     timestamptz,
  respondio_en   timestamptz,
  creado_en      timestamptz not null default now()
);

-- Una persona no puede entrar dos veces en el mismo envío. Es lo que pasa
-- cuando se seleccionan leads y alguien tiene tres.
create unique index if not exists ux_envio_destinatario
  on public.envio_destinatarios (envio_id, cliente_id);

-- Para mandar la siguiente tanda: los pendientes de un envío, en orden.
create index if not exists ix_destinatarios_pendientes
  on public.envio_destinatarios (envio_id, estado, id);

-- El webhook cruza por acá los acuses de entrega y lectura.
create index if not exists ix_destinatarios_wa
  on public.envio_destinatarios (wa_id) where wa_id is not null;

-- Y por teléfono, para marcar a quien contesta.
create index if not exists ix_destinatarios_telefono
  on public.envio_destinatarios (telefono, enviado_en desc);

-- --------------------------------------------------------------------- RLS

alter table public.envios              enable row level security;
alter table public.envio_destinatarios enable row level security;

drop policy if exists envios_ver          on public.envios;
drop policy if exists envios_crear        on public.envios;
drop policy if exists envios_editar       on public.envios;
drop policy if exists envios_borrar       on public.envios;
drop policy if exists destinatarios_ver   on public.envio_destinatarios;
drop policy if exists destinatarios_crear on public.envio_destinatarios;
drop policy if exists destinatarios_editar on public.envio_destinatarios;

/*
 * Los ve todo el equipo.
 *
 * Un envío masivo es del número de la escuela, no de una asesora: lo que sale
 * de ahí lo va a contestar cualquiera, y saber qué se mandó es lo que evita
 * que dos personas manden la misma campaña dos veces.
 */
create policy envios_ver on public.envios
  for select to authenticated using (true);

create policy envios_crear on public.envios
  for insert to authenticated with check (true);

create policy envios_editar on public.envios
  for update to authenticated using (true) with check (true);

-- Borrar un envío se lleva su historial. Como todo lo que borra de verdad en
-- este CRM, es de dirección.
create policy envios_borrar on public.envios
  for delete to authenticated using (public.es_admin());

create policy destinatarios_ver on public.envio_destinatarios
  for select to authenticated using (true);

create policy destinatarios_crear on public.envio_destinatarios
  for insert to authenticated with check (true);

create policy destinatarios_editar on public.envio_destinatarios
  for update to authenticated using (true) with check (true);

-- ------------------------------------------------------- cuántos hoy y a quién

/**
 * Cuántos mensajes masivos salieron en las últimas 24 horas.
 *
 * Meta le pone a cada número un tope de destinatarios únicos por día —1.000,
 * 10.000 o 100.000— y pasarse no da un error claro: los mensajes empiezan a
 * fallar y la calificación de calidad baja. La aplicación consulta esto antes
 * de empezar una campaña para poder decir «te quedan 640» en vez de arrancar
 * y romperse a la mitad.
 *
 * Cuenta personas distintas y no mensajes, que es como cuenta Meta.
 */
create or replace function public.enviados_hoy()
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select count(distinct d.cliente_id)::int
    from public.envio_destinatarios d
   where d.enviado_en > now() - interval '24 hours'
$$;

/**
 * ¿A esta persona ya le mandamos algo masivo hace poco?
 *
 * Para no repetirle. Recibir la misma campaña dos veces es la razón número uno
 * por la que alguien bloquea un número, y los bloqueos son lo que baja la
 * calificación que Meta le pone a la cuenta.
 */
create or replace function public.ya_le_mandamos(p_clientes bigint[], p_dias int default 7)
returns table (cliente_id bigint, cuando timestamptz, envio text)
language sql
stable
security definer
set search_path = ''
as $$
  select distinct on (d.cliente_id)
         d.cliente_id,
         d.enviado_en,
         e.nombre
    from public.envio_destinatarios d
    join public.envios e on e.id = d.envio_id
   where d.cliente_id = any(p_clientes)
     and d.enviado_en is not null
     and d.enviado_en > now() - (p_dias || ' days')::interval
   order by d.cliente_id, d.enviado_en desc
$$;

revoke execute on function public.enviados_hoy()                    from anon;
revoke execute on function public.ya_le_mandamos(bigint[], int)     from anon;
grant  execute on function public.enviados_hoy()                    to authenticated;
grant  execute on function public.ya_le_mandamos(bigint[], int)     to authenticated;

-- --------------------------------------------------------- el módulo nuevo

-- Para que se pueda esconder por rol como cualquier otra pantalla. Sin fila,
-- la regla del CRM es que se ve: nadie decidió nada todavía.
insert into public.modulos (clave, nombre, padre, orden)
values ('envios', 'Envíos', null, 16)
on conflict (clave) do update
  set nombre = excluded.nombre,
      orden  = excluded.orden;

commit;

-- ------------------------------------------------------------- cómo quedó

select
  case when to_regclass('public.envios') is not null
       then '✓ los envíos' else '· falta' end                        as envios,
  case when to_regclass('public.envio_destinatarios') is not null
       then '✓ con sus destinatarios' else '· falta' end             as destinatarios,
  case when exists (
    select 1 from information_schema.columns
     where table_schema = 'public' and table_name = 'clientes'
       and column_name = 'no_molestar'
  ) then '✓ y el «no molestar»' else '· falta' end                   as no_molestar,
  (select count(*) from public.clientes where not no_molestar)       as se_les_puede_escribir,
  (select count(*) from public.clientes
    where telefono is not null and trim(telefono) <> '')             as con_telefono,
  public.enviados_hoy()                                              as mandados_hoy;
