-- Ajustes aplicados sobre el esquema normalizado.
--
-- 1. Cierre de una fuga de datos: las vistas se habían creado como SECURITY
--    DEFINER (el comportamiento por defecto de Postgres), así que corrían con
--    los permisos de su creador y devolvían TODAS las filas a cualquiera con
--    la clave anónima, saltándose el RLS de las tablas.
-- 2. La vista de pipeline ahora expone también los id de cada catálogo, para
--    que la app pueda actualizar una oportunidad sin resolver por texto.
-- 3. Tablas de agenda, que el esquema original no contemplaba.

-- ------------------------------------------------------- vista de pipeline
-- Se recrea en vez de reemplazarse: `create or replace view` no permite
-- agregar columnas en medio del listado.
drop view if exists public.vw_pipeline;

create view public.vw_pipeline as
select o.id, o.codigo, o.fecha_registro, o.fecha_cierre,
       date_trunc('month', o.fecha_registro)::date as mes,
       o.cliente_id, c.nombre as cliente, c.telefono, c.correo,
       o.vendedor_id,   v.nombre  as vendedor,
       o.producto_id,   p.nombre  as producto, p.categoria,
       o.territorio_id, t.nombre  as territorio,
       o.canal_id,      ca.nombre as canal,
       o.etapa_id,      e.nombre  as etapa, e.orden as etapa_orden,
       o.estado_id,     s.nombre  as estado, s.es_final,
       o.valor_oportunidad, o.venta_cerrada, o.descuento_promocion
from public.oportunidades o
join public.clientes c   on c.id = o.cliente_id
left join public.vendedores  v  on v.id  = o.vendedor_id
left join public.productos   p  on p.id  = o.producto_id
left join public.territorios t  on t.id  = o.territorio_id
left join public.canales     ca on ca.id = o.canal_id
left join public.etapas      e  on e.id  = o.etapa_id
left join public.estados     s  on s.id  = o.estado_id;

-- security_invoker: la vista pasa a respetar el RLS de quien consulta.
alter view public.vw_pipeline     set (security_invoker = true);
alter view public.vw_kpi_vendedor set (security_invoker = true);
alter view public.vw_embudo       set (security_invoker = true);

-- search_path fijo: evita que un esquema malicioso en el search_path del
-- llamador secuestre las funciones que usa el trigger.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ------------------------------------------------------------------ agenda
create table if not exists public.tipos_evento (
  id           smallint primary key,
  nombre       text not null unique,
  codigo       text not null,
  color        text not null,
  duracion_min smallint not null default 30 check (duracion_min > 0),
  orden        smallint not null default 0
);

create table if not exists public.eventos (
  id             bigint generated by default as identity primary key,
  oportunidad_id bigint not null references public.oportunidades(id) on delete cascade,
  tipo_id        smallint not null references public.tipos_evento(id),
  vendedor_id    bigint references public.vendedores(id) on delete set null,
  inicia_en      timestamptz not null,
  duracion_min   smallint not null default 30 check (duracion_min > 0),
  canal          text not null default 'Llamada'
                 check (canal in ('Presencial','Llamada','WhatsApp','Meet')),
  estado         text not null default 'Pendiente'
                 check (estado in ('Pendiente','Realizado','No se presentó','Reagendado')),
  resultado      text,
  proxima_accion text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists idx_eventos_oportunidad on public.eventos (oportunidad_id);
create index if not exists idx_eventos_inicia      on public.eventos (inicia_en);
create index if not exists idx_eventos_vendedor    on public.eventos (vendedor_id);

drop trigger if exists trg_eventos_updated on public.eventos;
create trigger trg_eventos_updated before update on public.eventos
  for each row execute function public.set_updated_at();

insert into public.tipos_evento (id, nombre, codigo, color, duracion_min, orden) values
  (0,'Llamada / videollamada','LL','#2F6FA8',30,0),
  (1,'Visita o tour al campus','TC','#B85042',60,1),
  (2,'Clase muestra o demo','CM','#8A5AA8',120,2),
  (3,'Envío de propuesta','PR','#0F6E7A',15,3),
  (4,'Seguimiento','SG','#6B665F',20,4),
  (5,'Recordatorio de pago','PG','#9C7118',15,5),
  (6,'Reactivación a 6 meses','RE','#2F6B4F',20,6)
on conflict (id) do nothing;

alter table public.tipos_evento enable row level security;
alter table public.eventos      enable row level security;

drop policy if exists auth_read_tipos_evento on public.tipos_evento;
create policy auth_read_tipos_evento on public.tipos_evento
  for select to authenticated using (true);

drop policy if exists auth_all_eventos on public.eventos;
create policy auth_all_eventos on public.eventos
  for all to authenticated using (true) with check (true);
