begin;

-- Enlaces para pasarle una inscripción al área académica.
--
-- El asesor cierra la venta y tiene que decirle a académica a quién cobrarle y
-- cuánto. Hoy eso va por WhatsApp escrito a mano, y lo que se copia mal se
-- cobra mal. Con esto se manda un enlace y del otro lado se abre el detalle
-- tal como está en el CRM.
--
-- QUIÉN PUEDE ABRIRLO, que es la decisión importante de este archivo:
-- cualquiera que tenga el enlace, sin cuenta ni contraseña. Académica no usa
-- el CRM, así que pedirles sesión sería pedirles cuentas, y el enlace se
-- volvería inútil. A cambio:
--
--   * el `token` es un valor al azar de 24 bytes; no se adivina ni se recorre;
--   * vence solo a los 30 días, así que un enlace reenviado no queda abierto
--     para siempre;
--   * se puede anular sin borrar nada;
--   * la página pública muestra sólo lo de esa inscripción: nada de notas,
--     adjuntos, ni las otras oportunidades de la misma persona.
--
-- Aun así el enlace es una llave: quien lo tenga ve el nombre, el teléfono y
-- el monto de esa persona. Se manda por donde se mandaría el dato mismo.
--
-- Sólo crea cosas nuevas. Se puede correr con gente trabajando.

create table if not exists public.enlaces_pago (
  id             bigint generated by default as identity primary key,
  -- Lo que viaja en la URL. Único para poder buscarlo por ahí directo.
  token          text   not null unique,
  oportunidad_id bigint not null references public.oportunidades(id) on delete cascade,
  creado_por     uuid   references auth.users(id) on delete set null,
  creado_en      timestamptz not null default now(),
  vence_en       timestamptz not null default (now() + interval '30 days'),
  revocado       boolean not null default false,
  -- Para que el asesor sepa si del otro lado lo abrieron. Sin esto hay que
  -- preguntar por WhatsApp «¿te llegó?», que es la mitad de los mensajes.
  visto_en       timestamptz,
  vistas         integer not null default 0
);

create index if not exists ix_enlaces_pago_oportunidad
  on public.enlaces_pago (oportunidad_id, creado_en desc);

-- Un token corto sería adivinable a fuerza de probar. 24 bytes en base64url
-- dan 32 caracteres; se exige ese piso para que nadie lo genere más corto por
-- error desde otro lado.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'enlaces_pago_token_largo') then
    alter table public.enlaces_pago
      add constraint enlaces_pago_token_largo check (length(token) >= 32);
  end if;
end $$;

alter table public.enlaces_pago enable row level security;

-- Sólo el equipo del CRM crea, ve y anula enlaces.
--
-- No hay política para `anon` a propósito: la página pública no consulta con
-- la llave del navegador sino con la de servicio, desde el servidor y filtrando
-- por el token. Si hubiera una política de lectura para anónimos, cualquiera
-- podría pedir la tabla entera y quedarse con todos los enlaces de una vez.
drop policy if exists enlaces_pago_equipo on public.enlaces_pago;
create policy enlaces_pago_equipo on public.enlaces_pago
  for all to authenticated using (true) with check (true);

commit;
