begin;

-- Recordatorios que nacen de la bitácora.
--
-- ------------------------------------------------------------------------
-- QUÉ ES ESTO
-- ------------------------------------------------------------------------
--
-- Cuando un asesor escribe en una ficha una nota que dice «seguimiento de
-- pago» o «seguimiento de cierre», el CRM lee la nota, saca de ahí la fecha
-- —«que le llamen el 15 de cada mes»— y deja anotado el recordatorio. Esta
-- tabla es donde queda.
--
-- ------------------------------------------------------------------------
-- POR QUÉ UNA TABLA Y NO UNA COLUMNA MÁS EN LA OPORTUNIDAD
-- ------------------------------------------------------------------------
--
-- Los recordatorios de reserva son una propiedad de la ficha: hay uno, y sale
-- de la fecha del anticipo. Estos no. Una misma ficha puede tener uno de pago
-- todos los 15 y otro de cierre para el jueves, y los dos son ciertos a la
-- vez. Además llevan historia —cuál se atendió y cuándo— que en una columna no
-- entra.
--
-- ------------------------------------------------------------------------
-- LO QUE REPITE Y LO QUE NO
-- ------------------------------------------------------------------------
--
-- `dia_del_mes` nulo es un recordatorio de una sola vez: se atiende y se
-- termina. Con día puesto se repite, y al marcarlo atendido `proxima` salta al
-- mes siguiente en vez de cerrarse.
--
-- Un vencido no se corre solo hacia adelante. Es a propósito: si el del 15 de
-- marzo nadie lo atendió, tiene que verse en rojo y no reaparecer prolijo cada
-- mes como si el trabajo se hubiera hecho.
--
-- Crea una tabla y una vista. Se puede correr con gente trabajando, y dos
-- veces.

-- ------------------------------------------------------------------ tabla

create table if not exists public.seguimientos (
  id             bigint generated by default as identity primary key,
  oportunidad_id bigint not null references public.oportunidades(id) on delete cascade,

  -- De qué nota salió. `on delete set null` y no `cascade`: si alguien borra
  -- la nota, el compromiso de llamar al cliente no desaparece con ella.
  nota_id        bigint references public.oportunidad_notas(id) on delete set null,

  tipo           text not null check (tipo in ('pago', 'cierre')),

  -- Lo que decía la nota, recortado. Es lo que hace que el recordatorio se
  -- llame según la información de la nota y no «Seguimiento de pago» a secas,
  -- que no le dice al asesor qué habían quedado.
  detalle        text not null default '',

  proxima        date not null,
  dia_del_mes    smallint check (dia_del_mes between 1 and 31),
  dia_hasta      smallint check (dia_hasta between 1 and 31),

  creado_por     uuid references auth.users(id) on delete set null,
  hecho_en       timestamptz,
  creado_en      timestamptz not null default now()
);

-- El índice parcial es el que importa: la pantalla pregunta siempre por los
-- pendientes ordenados por fecha, y los atendidos se acumulan para siempre.
create index if not exists idx_seg_pendientes
  on public.seguimientos (proxima) where hecho_en is null;
create index if not exists idx_seg_op on public.seguimientos (oportunidad_id);

-- --------------------------------------------------------------- permisos

alter table public.seguimientos enable row level security;

do $$
declare
  hay_helper boolean := exists (
    select 1 from pg_proc where proname = 'puede_ver_oportunidad'
  );
  visible text;
begin
  -- El seguimiento sigue a su ficha: quien no puede ver la oportunidad tampoco
  -- ve lo que hay que hacer con ella. Es la misma regla que ya tienen las
  -- notas, escrita con la misma función para que no se puedan separar.
  --
  -- Si esa función todavía no existe —porque falta correr la migración de
  -- permisos— se cae a «cualquiera con sesión», que es exactamente lo que hoy
  -- pasa con el resto de las tablas en esa situación. Peor sería quedarse sin
  -- políticas y que nadie viera nada.
  visible := case when hay_helper
                  then 'public.puede_ver_oportunidad(oportunidad_id)'
                  else 'true' end;

  execute 'drop policy if exists seguimientos_ver on public.seguimientos';
  execute format(
    'create policy seguimientos_ver on public.seguimientos
       for select to authenticated using (%s)', visible);

  execute 'drop policy if exists seguimientos_crear on public.seguimientos';
  execute format(
    'create policy seguimientos_crear on public.seguimientos
       for insert to authenticated with check (%s)', visible);

  -- Marcar atendido y posponer son actualizaciones, y las hace quien atiende
  -- la ficha: las mismas manos que pueden verla.
  execute 'drop policy if exists seguimientos_actualizar on public.seguimientos';
  execute format(
    'create policy seguimientos_actualizar on public.seguimientos
       for update to authenticated using (%s) with check (%s)', visible, visible);

  execute 'drop policy if exists seguimientos_borrar on public.seguimientos';
  if hay_helper then
    execute
      'create policy seguimientos_borrar on public.seguimientos
         for delete to authenticated
         using (public.es_admin() or creado_por = (select auth.uid()))';
  else
    execute
      'create policy seguimientos_borrar on public.seguimientos
         for delete to authenticated using (true)';
  end if;
end $$;

-- ----------------------------------------------------------------- vista
--
-- La pantalla necesita el nombre del cliente, el del asesor y el teléfono al
-- que hay que llamar. Sin la vista serían cuatro consultas por recordatorio.
--
-- `security_invoker` es lo que hace que la vista no sea un agujero: mira con
-- los permisos de quien pregunta, así que un asesor sigue viendo sólo lo suyo
-- aunque la vista junte todas las tablas.

drop view if exists public.vw_seguimientos;

create view public.vw_seguimientos as
select s.id,
       s.oportunidad_id,
       s.nota_id,
       s.tipo,
       s.detalle,
       s.proxima,
       s.dia_del_mes,
       s.dia_hasta,
       s.hecho_en,
       s.creado_en,
       s.creado_por,
       o.codigo,
       o.vendedor_id,
       v.nombre as vendedor,
       c.nombre as cliente,
       c.telefono,
       p.nombre as producto
  from public.seguimientos s
  join public.oportunidades o on o.id = s.oportunidad_id
  join public.clientes      c on c.id = o.cliente_id
  left join public.vendedores v on v.id = o.vendedor_id
  left join public.productos  p on p.id = o.producto_id;

alter view public.vw_seguimientos set (security_invoker = true);

-- ------------------------------------------------------------- en vivo

do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  -- Sin esto, el asesor que anota un seguimiento no lo ve aparecer en el reloj
  -- hasta el refresco siguiente, y peor: la gerencia mirando la misma ficha no
  -- se entera nunca hasta recargar.
  if not exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'seguimientos'
  ) then
    alter publication supabase_realtime add table public.seguimientos;
    raise notice 'seguimientos publicada para cambios en vivo';
  else
    raise notice 'seguimientos ya estaba publicada';
  end if;
end $$;

commit;
