begin;

-- ============================================================================
-- Llamadas de WhatsApp
-- ============================================================================
--
-- Lo que pidió la escuela: «acabo de activar la opción de llamadas para
-- WhatsApp API [...] se podrían hacer llamadas a clientes colocando un botón de
-- llamar y, además, poder tener la opción de recibir llamadas».
--
-- Y la condición que manda sobre todo el diseño:
--
--   «Aquí lo que no quiero es que vayan a afectar las llamadas entrantes al
--    momento que estén escribiendo o interactuando en el CRM. Me gustaría que
--    apareciera como pop up la llamada y contestarla, pero en los demás
--    dispositivos se minimice y se visualice en una esquina.»
--
-- ----------------------------------------------------------------------------
-- POR QUÉ HACE FALTA UNA TABLA Y NO ALCANZA CON EL WEBHOOK
-- ----------------------------------------------------------------------------
--
-- El audio no pasa por acá. Meta habla WebRTC: la voz va del navegador de la
-- asesora a Meta y de Meta al teléfono del cliente, directo. Lo único que
-- viaja por nuestro servidor es el papelito que las dos puntas necesitan para
-- encontrarse —el SDP— y las órdenes de contestar, rechazar y colgar.
--
-- Ese papelito llega por el webhook, que corre en el servidor y no tiene forma
-- de hablarle a un navegador. La tabla es el puente: el webhook escribe la
-- fila, Supabase la publica por websocket, y a los navegadores que están
-- abiertos les suena el teléfono.
--
-- Es también lo que hace que el pop-up aparezca en UNA pantalla y en las demás
-- una tarjeta chiquita: todos ven la misma fila, y cada navegador decide qué
-- hacer con ella según de quién es el hilo y si esa persona está escribiendo.
--
-- ----------------------------------------------------------------------------
-- EL RELOJ
-- ----------------------------------------------------------------------------
--
-- Meta da entre 30 y 60 segundos desde que avisa hasta que da la llamada por
-- no contestada. En ese rato tiene que entrar el webhook, escribirse esta
-- fila, salir el aviso por websocket, sonar el teléfono, decidir la persona y
-- volver la respuesta a Meta. Por eso la fila se escribe con lo mínimo y de
-- una sola vez: todo lo que no sea indispensable para que suene se hace
-- después.
--
-- ----------------------------------------------------------------------------

create table if not exists public.llamadas (
  id              bigint generated by default as identity primary key,

  -- El id que le puso Meta a la llamada. Es con lo que se le contesta, y es
  -- lo que evita atender dos veces la misma cuando el webhook se reintenta.
  call_id         text not null unique,

  -- El hilo de la bandeja. Nulo sólo si llama alguien de quien no se pudo
  -- resolver la conversación; la llamada suena igual, que es lo que importa.
  conversacion_id bigint references public.conversaciones(id) on delete cascade,

  -- Sólo dígitos y con código de país, igual que en `conversaciones`.
  telefono        text not null,

  /*
   * De quién es el hilo, y cómo se llama quien llama, COPIADOS ACÁ.
   *
   * Parece redundante —los dos están en `conversaciones`— y no lo es: es lo
   * que hace que la llamada suene bien en la pantalla de todo el equipo.
   *
   * `conversaciones` no se ve entera. Su política deja ver sólo los hilos
   * propios, los sin asignar y los de quien puede ver todo. Está bien que sea
   * así para la bandeja, pero una llamada tiene que sonar en TODAS las
   * pantallas —alguien tiene que poder atenderla si la dueña salió— y una
   * pantalla que no puede leer el hilo tampoco puede saber de quién es.
   *
   * Sin esto pasa lo peor posible: como no encuentra dueño, la trata como sin
   * asignar y le tira el pop-up encima a TODO el equipo, que es exactamente lo
   * que la escuela pidió evitar.
   *
   * Se copian una vez, al entrar la llamada, y no se vuelven a mirar. Si
   * después alguien reasigna el hilo, la llamada que ya está sonando sigue
   * siendo de quien era cuando entró, que es lo correcto: reasignar en medio
   * de un timbre no debería mover el teléfono de escritorio.
   */
  vendedor_id     bigint references public.vendedores(id) on delete set null,
  -- Como se lo conoce: el nombre de su WhatsApp, o el de su ficha.
  nombre          text,

  direccion       text not null check (direccion in ('entrante', 'saliente')),

  /*
   * En qué anda.
   *
   *   sonando      Está sonando. Es el único estado que interrumpe a nadie.
   *   contestando  Alguien la agarró y se está armando el audio.
   *   en_curso     Hablando.
   *   terminada    Colgó alguno de los dos, después de haber hablado.
   *   rechazada    Se apretó «Rechazar».
   *   perdida      Nadie la atendió y se venció el plazo de Meta.
   *   fallida      No se pudo establecer.
   *
   * `terminada`, `rechazada`, `perdida` y `fallida` son finales: una llamada
   * que llegó ahí no vuelve a sonar aunque el webhook se reintente.
   */
  estado          text not null default 'sonando'
                  check (estado in ('sonando', 'contestando', 'en_curso',
                                    'terminada', 'rechazada', 'perdida', 'fallida')),

  /*
   * El SDP de la otra punta.
   *
   * En una entrante es la oferta que manda Meta y el navegador la contesta;
   * en una saliente es la respuesta de Meta a la oferta que mandamos. No es
   * un secreto —describe códecs y direcciones de red, no contenido— pero
   * igual queda detrás de RLS: sólo se ve con sesión abierta.
   */
  sdp_remoto      text,
  sdp_tipo        text check (sdp_tipo in ('offer', 'answer')),

  -- Quién la agarró. Se pone con `atender_llamada`, que es lo que impide que
  -- dos asesoras contesten la misma.
  atendida_por    uuid references auth.users(id) on delete set null,
  atendida_en     timestamptz,

  termino_en      timestamptz,
  -- La que informa Meta al terminar. Es la que vale para el registro: cuenta
  -- desde que se estableció el audio, no desde que empezó a sonar.
  duracion_seg    integer,
  -- Texto de Meta cuando algo salió mal, para que un fallo se pueda entender
  -- después sin mirar los registros del servidor.
  motivo          text,

  creado_en       timestamptz not null default now()
);

-- Se piden siempre «las que están sonando ahora», y por hilo al abrir uno.
create index if not exists ix_llamadas_vivas
  on public.llamadas (creado_en desc)
  where estado in ('sonando', 'contestando', 'en_curso');

create index if not exists ix_llamadas_conversacion
  on public.llamadas (conversacion_id, creado_en desc);

-- --------------------------------------------------------------------- RLS

alter table public.llamadas enable row level security;

drop policy if exists llamadas_ver     on public.llamadas;
drop policy if exists llamadas_atender on public.llamadas;

/*
 * Las ve todo el equipo, igual que la bandeja.
 *
 * No es una concesión: es el requisito. Una llamada tiene que sonar en todas
 * las pantallas abiertas, porque quien está libre para atenderla no es
 * siempre la dueña del hilo. Quién ve el pop-up y quién la tarjeta de la
 * esquina lo decide la aplicación mirando la misma fila, no esconderle la
 * fila a nadie.
 */
create policy llamadas_ver on public.llamadas
  for select to authenticated using (true);

/*
 * Desde el navegador se puede cambiar el estado, pero no inventar una llamada.
 *
 * No hay política de insert a propósito: las filas las escribe el webhook con
 * la clave de servicio —para las entrantes— y la acción de servidor que llama
 * a Meta —para las salientes—. Sin esto, cualquiera con el inspector abierto
 * podría hacer sonar el teléfono de todo el equipo con una llamada que no
 * existe.
 */
create policy llamadas_atender on public.llamadas
  for update to authenticated using (true) with check (true);

-- ------------------------------------------------------- agarrar la llamada
--
-- Suena en cinco pantallas y dos personas aprietan «Contestar» a la vez. Sin
-- candado las dos le mandarían a Meta su propia respuesta de audio: una de las
-- dos se queda con el micrófono abierto contra una llamada que agarró otra, y
-- del lado del cliente el audio sale roto o no sale.
--
-- Esto lo resuelve la base, que es donde se puede: el `where atendida_por is
-- null` sólo lo cumple la primera, y la segunda recibe `conseguida = false` y
-- le muestra «la atendió Katya» en vez del pop-up.
--
-- Devuelve además quién la tiene, para poder decirlo con nombre.
-- ----------------------------------------------------------------------------
create or replace function public.atender_llamada(p_call_id text)
returns table (conseguida boolean, quien uuid)
language plpgsql
security definer
set search_path = public
as $$
declare v_yo uuid := auth.uid();
begin
  update public.llamadas
     set atendida_por = v_yo,
         atendida_en  = now(),
         estado       = 'contestando'
   where call_id = p_call_id
     and atendida_por is null
     and estado = 'sonando';

  if found then
    return query select true, v_yo;
  else
    return query
      select false, l.atendida_por from public.llamadas l where l.call_id = p_call_id;
  end if;
end $$;

grant execute on function public.atender_llamada(text) to authenticated;

-- --------------------------------------------------------------- cerrarla
--
-- Sólo hacia adelante. Meta manda los avisos desordenados —el de terminada
-- puede llegar antes que el de establecida—, y sin esta condición una llamada
-- que ya terminó volvería a decir «en curso» y el teléfono sonaría de nuevo.
-- ----------------------------------------------------------------------------
create or replace function public.cerrar_llamada(
  p_call_id  text,
  p_estado   text,
  p_duracion integer default null,
  p_motivo   text default null
) returns void
language sql
security definer
set search_path = public
as $$
  update public.llamadas
     set estado       = p_estado,
         termino_en   = coalesce(termino_en, now()),
         duracion_seg = coalesce(p_duracion, duracion_seg),
         motivo       = coalesce(p_motivo, motivo)
   where call_id = p_call_id
     and estado in ('sonando', 'contestando', 'en_curso');
$$;

grant execute on function public.cerrar_llamada(text, text, integer, text) to authenticated;

-- ------------------------------------------------------- avisos en vivo
--
-- Sin esto la tabla existe pero nadie se entera de que entró una llamada:
-- suscribirse no da error, simplemente no llega nada nunca. Es la diferencia
-- entre que suene el teléfono y que la llamada se pierda.
do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;

  if not exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'llamadas'
  ) then
    alter publication supabase_realtime add table public.llamadas;
  end if;
end $$;

commit;

-- ------------------------------------------------------------- cómo quedó

select
  case when to_regclass('public.llamadas') is not null
       then '✓ la tabla está' else '· falta' end                        as tabla,
  case when exists (
    select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname = 'atender_llamada'
  ) then '✓ con candado para no atender dos veces' else '· falta' end   as candado,
  case when (
    select count(*) from pg_policies
     where schemaname = 'public' and tablename = 'llamadas'
  ) = 2 then '✓ se ven, y no se pueden inventar' else '⚠ REVISAR' end   as permisos,
  case when exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'llamadas'
  ) then '✓ el teléfono va a sonar' else '⚠ NO VA A SONAR' end          as en_vivo,
  (select count(*) from public.llamadas)                                as llamadas;
