-- Registro de las bases importadas.
--
-- Hasta ahora una importación dejaba las filas en `clientes` y
-- `oportunidades` y nada más: no quedaba rastro de qué archivo las trajo ni
-- cuándo. Esta tabla guarda ese encabezado, y cada oportunidad apunta a él.

create table if not exists public.importaciones (
  id          bigint generated by default as identity primary key,
  archivo     text not null,
  -- Cuántas filas se dieron de alta en esta corrida.
  filas       integer not null default 0,
  -- Quién la subió. Se conserva la importación aunque la cuenta se borre.
  creado_por  uuid references auth.users(id) on delete set null,
  creado_en   timestamptz not null default now()
);

create index if not exists ix_importaciones_creado_en
  on public.importaciones (creado_en desc);

-- `set null` y no `cascade`: borrar el registro de una base no debe borrar
-- los clientes que trajo.
alter table public.oportunidades
  add column if not exists importacion_id bigint
  references public.importaciones(id) on delete set null;

create index if not exists ix_oportunidades_importacion
  on public.oportunidades (importacion_id);

-- ---------------------------------------------------------------- vista
--
-- `created_at` e `importacion_id` se suman a la vista para que la pantalla
-- pueda agrupar por carga sin una consulta aparte. Hay que recrearla porque
-- `create or replace view` no admite agregar columnas en el medio.

drop view if exists public.vw_pipeline;

create view public.vw_pipeline as
select o.id, o.codigo, o.fecha_registro, o.fecha_cierre,
       date_trunc('month', o.fecha_registro)::date as mes,
       o.cliente_id, c.nombre as cliente, c.telefono, c.correo,
       o.vendedor_id,   v.nombre  as vendedor,
       o.producto_id,   p.nombre  as producto, p.categoria,
       o.territorio_id, t.nombre  as territorio,
       o.canal_id,      ca.nombre as canal,
       o.etapa_id,      e.nombre  as etapa, e.orden as etapa_orden,
       o.estado_id,     s.nombre  as estado, s.es_final,
       o.valor_oportunidad, o.venta_cerrada, o.descuento_promocion,
       o.created_at, o.importacion_id
from public.oportunidades o
join public.clientes c   on c.id = o.cliente_id
left join public.vendedores  v  on v.id  = o.vendedor_id
left join public.productos   p  on p.id  = o.producto_id
left join public.territorios t  on t.id  = o.territorio_id
left join public.canales     ca on ca.id = o.canal_id
left join public.etapas      e  on e.id  = o.etapa_id
left join public.estados     s  on s.id  = o.estado_id;

-- La vista respeta el RLS de quien consulta, igual que antes.
alter view public.vw_pipeline set (security_invoker = true);

-- ---------------------------------------------------------------- RLS

alter table public.importaciones enable row level security;

drop policy if exists auth_all_importaciones on public.importaciones;
create policy auth_all_importaciones on public.importaciones
  for all to authenticated using (true) with check (true);
